serokell/tezos-packaging

.buildkite/check-trailing-whitespace.sh
.buildkite/pipeline.yml
.crossref-verifier.yaml
.github/CONTRIBUTING.md
.github/pull_request_template.md
.reuse/dep5
LICENSES/MPL-2.0.txt
README.md
default.nix
nix/default.nix
nix/fix-mainnet.patch
nix/fix.patch
nix/musl-bin.nix
nix/static.nix
packageDeb.nix
packageRpm.nix

We have nix expressions for building static `tezos-client` binary. Having this executable separate
from the `babylonnet.sh` or `mainnet.sh` scripts will be useful for tezos community.
This PR provides initial repository set up with instructions on how to build static `tezos-client` binary and
`.rpm/deb` packages based on this binary. Also set up CI to produce these packages and binary.

[TM-359] Initial repo setup

---

README.md

Problem: Both repo and CI pipeline were renamed, however, README has
link to the old pipeline (it still works, btw).
Solution: Update link to renamed buildkite pipeline.
Resolves #3

Change link to CI

---

.github/CONTRIBUTING.md
README.md

Problem: We are going to package other tezos-related binaries as well,
thus `tezos-client-packaging` is not the best name for repo.
Solution: Rename it once again, now to `tezos-packaging`
Also pipeline on buildkite was renamed
~Resolves~ Relates #14
https://issues.serokell.io/issue/OPS-901

[#14] Rename repo

---

default.nix
packageDeb.nix
packageRpm.nix

Problem: Currently we run linux VM in order to generate .deb or .rpm
package. However, this is slow and consumes a lot of resoures.
Solution: Run `dpkg-deb` and `rpmbuild` directly in nix.
Maybe _resolves_ #10

[#10] Do not use VM during packaging

---

.buildkite/pipeline.yml
README.md
default.nix
packageRpm.nix

Problem: We want to upload our rpm package to copr, we need `.src.rpm`
package for this.
Solution: Generate it along with `.rpm` package.
Also, update installation instructions for Fedora. 
Resolves #12

[#12] srpm generation and Fedora copr

---

default.nix
nix/default.nix

Problem: All packages have MPL-2.0 license, however, it is a bit
incorrect.
Solution: Use license from tezos repo instead.
Resolves #16

[#16] Update license in packages

---

nix/default.nix

Produced static binaries appear to be well amenable to
packing with [upx](https://upx.github.io/) tool. So we compress them to reduce size of the
resulted binaries and packages.
`tezos-client` seems to work as expected, upx compressed the binary approximately at 70%
Resolves #23

[#23] Compress binaries with upx

---

.buildkite/pipeline.yml
README.md
default.nix
release.nix
scripts/autorelease.sh

Problem: We want an easier and more convenient way to get static binaries
(also packages, but this is secondarily, since we have PPAs).
Solution: Add autorelease script that produces github prerelease with
all closures (binaries and packages).
Resolves #11

[#11] Add autorelease script

---

.buildkite/pipeline.yml
Makefile
README.md
default.nix
nix/default.nix
nix/fix-babylonnet.patch
nix/fix-mainnet.patch
packageRpm.nix
scripts/autorelease.sh

Tezos software includes more executables than just `tezos-client`. We want to package them as well.
For now, in this PR we only build static binaries for them 
(specifically `tezos-client`, `tezos-admin-client`, `tezos-node`, `tezos-baker`, `tezos-accuser`, `tezos-endorser`, `tezos-signer`, and `tezos-protocol-compiler`).
TODO:
~* Package them into `.deb` and `.rpm` as well as `tezos-client`.~
~* Update usage instructions.~
Resolves #14

[#14] Package more tezos binaries

---

default.nix
nix/default.nix

Problem: In one of our projects we want to provide patched static
tezos-binaries.
Solution: Make patches configurable.
None

Make source patches configurable

---

README.md
release.nix
scripts/autorelease.sh

Problem: Each release contains `packages-deb.tar.gz` and
`packages-rpm.tar.gz` which occupy more than 150 MB in total and are not
really useful because they are accessible from ppa and copr.
Solution: Exclude them from releases.
Resolves #34

[#34] Remove deb and rpm from releases

---

README.md
default.nix
packageRpm.nix
packageSourceDeb.nix
release.nix

Problem: Currently, source package generation for ubuntu is performed
manually, soon (after #14 is resolved) we will have much more stuff to package 
and publish on launchpad.
Solution: Automate deb source packages generation using nix.
At this point, we are going back to the package generation inside Ubuntu VM.
Unfortunately, `dpkg-buildpackage` uses some hardcoded filepaths and
also require some dependencies, which are specific only for debian-based
repositories, achieving this without VM will be extremely painful.
Since launchpad and copr repo updates will not happen very often, we
can generate ubuntu stuff using VM. Also, we are not going to generate
it in CI, because source packages are not really useful for end-users.
Source packages generation for Fedora and rpm was also slightly …

[#19] Generate source packages using nix

---

.buildkite/pipeline.yml
default.nix
nix/fix-master.patch
release.nix

Problem: Dune files for `tezos-{accuser, baker, endorser}-006-PsCARTHA`
were lacking flags required for static building. This caused errors
when trying to run built executables.
Solution: Add flags.
Resolves #38

[#38] Fix carthagenet specific binaries

---

default.nix

In other projects where nix is used it is more convenient to consume binaries in a form of unpacked derivation rather than tarball.
Resolves #

Add derivation attribute to default.nix

---

default.nix
protocols.json

Problem: When starting from scratch `tezos-node` required information
about base chain protocols. Currently, we ignore all protocols except
006, this causes `tezos-node run` to fail.
Solution: Unignore `genesis`, `genesis-carthagenet`, `000-Ps9mPmXa`.
Resolves #48

[#48] Unignore base protocols

---

deb.nix
debSource.nix
default.nix
nix/sources.json
release.nix
rpm.nix

Problem: Tezos now uses some versioning. `v7.0-rc1` recently was
released. We should use this versioning.
Solution: Optionally replace commit hash in the package version with
tag in case we are using sources that are not from the master branch
(git treats release tags the same way as branches).
We still want to be able to do multiple releases within single tezos
release or make releases that are based on fresh tezos code that wasn't
released.
Resolves #47

[#47] Tezos releases in versioning

---

hacks.nix

see #52 
TLDR: 
```
$ tezos-client -S -A mainnet-tezos.giganode.io -P 443 rpc get /chains/main/blocks/head/protocols
Error:
Rpc request failed:
- meth: GET
- uri: https://mainnet-tezos.giganode.io:443/describe/chains/main/blocks/head/protocols?recurse=no
- error: Unable to connect to the node: "No SSL or TLS support compiled into Conduit"
```
Build conduit with tls support.
Now:
```
$ tezos-client -S -A mainnet-tezos.giganode.io -P 443 rpc get /chains/main/blocks/head/protocols
{ "protocol": "PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb",
"next_protocol": "PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb" }
```
Resolves #52

Add tls to conduit

---

default.nix
docker/Dockerfile
nix/nix/sources.json

Problem: Tezos recently had new v7.2 release, we should update our
packaging as well.
Solution: Bump tezos to v7.2 :shrug:.
Relates #26

[#26] Bump tezos to v7.2

---

docker/build/Dockerfile
nix/nix/sources.json

Problem: a new tezos version is released. We want to keep up with upstream updates.
Solution: update revision of tezos to the v7.3 tag.
Relates to #26

[#26] Update tezos version to 7.3

---

.buildkite/pipeline.yml
.reuse/dep5
README.md
docker/docker-ubuntu-packages.sh
docker/package/Dockerfile
docker/package/defaults/tezos-accuser.conf
docker/package/defaults/tezos-baker.conf
docker/package/defaults/tezos-endorser.conf
docker/package/defaults/tezos-node.conf
docker/package/package_generator.py
docker/package/scripts/tezos-accuser-start
docker/package/scripts/tezos-baker-start
docker/package/scripts/tezos-endorser-start
docker/package/scripts/tezos-node-start
docker/package/systemd/tezos-accuser.service
docker/package/systemd/tezos-baker.service
docker/package/systemd/tezos-endorser.service
docker/package/systemd/tezos-node.service

Draft. Untested. Pushing early to review as we go.
The aim of this PR is to add systemd service units for the Tezos node, baker, and accuser, along with any scripts necessary to get them up.
The shell script code has been copied from upstream: https://gitlab.com/tezos/tezos/-/blob/v7.2/scripts/docker/entrypoint.inc.sh
Modified to baseless assumptions for correct paths on Ubuntu.
There is a related PR to tezos-infra to spin up a Ubuntu 20.04 machine to test these units.
https://github.com/serokell/tezos-infra/pull/26
https://issues.serokell.io/issue/TM-429
Resolves #68
Resolves #56

[TM-429] WIP Systemd units and launch scripts

---

docker/README.md
docker/build/Dockerfile.aarch64
docker/build/build-libusb-and-hidapi.sh
docker/build/build-tezos.sh
docker/docker-static-build.sh

Problem: We want to support rpi and arm architecture in general.
Unfortunately, it's quite nontrivial to use opam and ocaml on armv7l,
since OCaml 4.09.1 has issues with building on this architecture.
Solution: Add static binaries building for 64bit arm architecture via
qemu + aarch64 docker alpine image.
This PR resolves only part of #64.
Needs to be done:
* Build aarch64 binaries automatically on the remote arm machine in CI.
* Include built binaries to the releases.
* (?) Provide native `.deb` packages with tezos-binaries for RPI.
Resolves part of #64

[#64] Add aarch64 static binaries building

---

.buildkite/pipeline.yml
protocols.json
tests/tezos-binaries.nix

Problem: We doesn't compile all protocols for nix binaries, this lead to
a problem when bootstrapping mainnet node, it says that old protocols
are missing during block validation.
Solution: Allow all old protocols.
https://issues.serokell.io/issue/OPS-997

Allow all old protocols

---

scripts/autorelease.sh
scripts/shell.nix

Problem: `nix-shell -p` requires nixpkgs to be in
`NIX_PATH`, which we removed earlier.
Solution: Use shell.nix file instead of using `-p` option.
Resolves #

Fix auto releases

---

docker/build/static_libs.patch
docker/docker-static-build.sh
nix/nix/sources.json
protocols.json

The new tezos version arrived. 
Now tezos has two actual protocol versions: 006 and 007 (currently used only on delphinet).
Relates #26

[#26] tezos v7.4

---

.buildkite/pipeline.yml
default.nix
release.nix
scripts/autorelease.sh

Problem: We want to have automated way for building static arm binaries.
Solution: Use dedicated buildkite-agent which is run on arm64 machine
for building static arm binaries.
~Currently depends on [OPS-1058](https://issues.serokell.io/issue/OPS-1058), pipeline setup
can change a bit once this issue is resolved.~
Resolves #64

[#64] Arm building in CI

---

.buildkite/pipeline.yml
docker/README.md
docker/docker-static-build.sh
docker/docker-ubuntu-packages.sh
docker/package/Dockerfile

Problem: We cannot longer use docker in our CI pipeline.
Solution: Allow using podman instead of docker, use it in CI and update
instructions to mention an ability to use podman.
https://issues.serokell.io/issue/OPS-1063
https://issues.serokell.io/issue/OPS-1064

Allow using podman instead of docker

---

.buildkite/pipeline.yml
nix/nix/sources.json

Problem: Builds fail in Nix versions 2.4 and above due to a change in default handling of `ref`
Solution: Use a more explicit `ref` for the `tezos` source
None

Update tezos ref to fix compatibility with newer Nix versions

---

default.nix

Problem: In #92 tezos sources ref was changed, however, meta builder
wasn't updated, thus autoreleasing was broken.
Solution: Fix meta building.
None

Fix version fetching in autoreleases 

---

nix/build/ocaml-overlay.nix

Problem: There is invalid default path in ocaml-overlay.nix.
However, we want to use this overlay in on of our projects.
Solution: Fix default path.
https://issues.serokell.io/issue/OPS-997

Fix default sources in ocaml-overlay.nix

---

docker/package/package_generator.py
meta.json

Problem: Ledger backend, as well as tls support, is provided
via optional opam dependencies, so they're not included by default.
Solution: Make it possible to explicitly list which optional
dependencies should be bundled along with the desired tezos package.
Add tls and ledger support to all required packages.
TODO: Now we need to bump ubuntu packages versions since the packages sources were updated
(there are new prefetched opam dependencies in them). We should find out what is the best strategy to do that.
See #95, ubuntu packages will be updated only after it's resolved
Resolves #87
Resolves #89

[#89][#87] Package along with optional deps

---

docker/package/package_generator.py
meta.json

Problem: Current ubuntu versioning scheme is incorrect and may
confuse users.
Solution: Use proper versioning scheme:
`<package-name>_<upstream-version>-0ubuntu<release-number>.`
Resolves #95

[#95] Change ubuntu packages versioning

---

.buildkite/pipeline.yml

Problem: Sometimes packages building can stuck due to some
weird opam errors. Such behaviour can silently block CI.
Solution: Normally, each step should take more than 10-15 minutes, and
we double the timeout just in case.
None

Add timeout for packages building

---

docker/build/static_libs.patch
docker/docker-static-build.sh
docker/package/packages.py
nix/build/release-binaries.nix
tests/test_script.py
tests/tezos-binaries.nix

Tezos-codec is a binary to decode and encode JSON. Added the
ability to create static binaries using docker and nyx. It is also possible to build packages using docker.
nope
Resolves #85

#85 Add tezos-codec packeg

---

scripts/autorelease.sh
scripts/shell.nix

Problem: There is an official CLI from github, now it can handle
releases.
Solution: Switch to it from hub tool.
Resolves #97

[#97] Switch autoreleases from hub to gh

---

.buildkite/pipeline.yml
docker/package/Dockerfile-fedora
docker/package/Dockerfile-ubuntu

Problem: Podman turned out to be quite unreliable.
Solution: Switch back to docker, since we now have a dedicated agent
with access to the docker.
None

Switch back to docker

---

.buildkite/pipeline.yml
README.md
docker/README.md
docker/package/packages.py
protocols.json
tests/test_script.py
tests/tezos-binaries.nix

Problem: 007 protocol was activated on mainnet and carthagenet will die
soon, so it doesn't make much sense to maintain 006 protocol-specific
binaries and packages.
Solution: Move 006 from active to allowed in protocols.json and update other
files accordingly.
Currently based on #110 
None

Deactivate 006 protocol

---

.buildkite/pipeline.yml
default.nix
release.nix
scripts/autorelease.sh

Problem: Buildkite agent was moved to another server and the file with
token now isn't presented in the filesystem.
Solution: Don't rely on file and fetch token directly from vault.
None

Fix autoreleasing once again

---

README.md
docker/package/defaults/tezos-signer.conf
docker/package/model.py
docker/package/package_generator.py
docker/package/packages.py
docker/package/scripts/tezos-signer-start

Problem: tezos-signer can be run as a signing daemon in one of four
modes.
Solution: Add services for each signer daemon mode: over TCP socket,
over Unix socket, over HTTP, and over HTTPS.
Resolves #100

[#100] tezos-signer services

---

README.md
docker/build/build-tezos.sh
docker/build/static_libs.patch
docker/docker-static-build.sh
nix/build/release-binaries.nix
nix/build/static-overlay.nix
nix/default.nix

Problem: There is a program called tezos-sandbox that can be helpful
for setting up and testing various scenarios with the blockchain.
Also, it's not built by default, however, it's still useful for the
developers
Solution: Build and bundle static tezos-sandbox binary.
Suddenly, there is no opam package for tezos-sandbox, thus we cannot
provide native Ubuntu and Fedora packages with tezos-sandbox.
Resolves #109

[#109] Static tezos-sandbox binary

---

.buildkite/pipeline.yml
docker/README.md
docker/docker-tezos-packages.sh
docker/package/package_generator.py

Problem: Launchpad requires the source archive to be the same for
the same package version, but a different release number.
Solution: Allow using existing source archive when building ubuntu
packages.
Resolves #118

[#118] Simplify Ubuntu release updating

---

docker/README.md
release.nix
scripts/autorelease.sh
scripts/shell.nix

We want to provide some way for people to check whether binaries/packages they're using are genuine
and created by Serokell.
This PR adds sha256 sum calculation along with PGP signing for all autorelease artifacts.
Also, this PR adds instruction about how native packages should be signed before publishing.
Resolves #114

[#114] Sign and hash artifacts

---

.buildkite/pipeline.yml
meta.json
nix/nix/sources.json

Bump tezos to v7.5.
Suspend native packaging for now, because tezos packages in opam repository are still outdated
Resolves #

v7.5 release

---

Formula/tezos-accuser-007-PsDELPH1.rb
Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-007-PsDELPH1.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-007-PsDELPH1.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: MacOS users don't want to build Tezos from scratch.
Solution: Provide bottles with Tezos binaries for ЬacOS Catalina.
Resolves #

Add catalina bottles hashes

---

.buildkite/pipeline.yml

Problem: PR to opam-repository was merged. CI now should be capable of
checking native packaging.
Solution: Uncomment CI steps related to native packaging.
Resolves #

Resurrect v8.2 native packaging

---

Formula/tezos-accuser-007-PsDELPH1.rb
Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-007-PsDELPH1.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-007-PsDELPH1.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: MacOS users don't want to build Tezos from scratch.
Solution: Provide bottles with Tezos binaries for MacOS Mojave.
Resolves #

Add mojave bottles hashes

---

README.md
docker/package/packages.py
docker/package/scripts/tezos-node-start

Problem: We want to run node in some custom network. A custom network
can be defined via a custom node config file.
Solution: Using a variable CUSTOM_NODE_CONFIG, you can specify the path
to the node configuration file.
None
Resolves #99

[#99] Support custom networks within the node service

---

docker/package/model.py
docker/package/package_generator.py
docker/package/packages.py

Sapling params are a hard runtime dependency for some of the Tezos binaries.
This PR adds a native package that wraps the required `sapling-spend.params` and `sapling-output.params`.
This package is later used as a dependency for `tezos-client`, `tezos-node` and `tezos-baker` packages.
Resolves #132 

[#132] Native package with sapling params

---

docker/docker-tezos-packages.sh
docker/package/defaults/tezos-accuser.conf
docker/package/defaults/tezos-baker.conf
docker/package/defaults/tezos-endorser.conf
docker/package/model.py
docker/package/package_generator.py
docker/package/packages.py

Problem: We want users and default data directories to be created
automatically along with the package installation.
Solution: Add scripts that do that in the package post-installation
stage.
Currently based on #142 
Resolves #133

[#133] Native packages postinstalls

---

docker/docker-tezos-packages.sh
docker/package/defaults/tezos-accuser.conf
docker/package/defaults/tezos-baker.conf
docker/package/defaults/tezos-endorser.conf
docker/package/model.py
docker/package/packages.py
meta.json

Custom postinst scripts were added to some of the packages in #143. However, there are some bugs in them:
* Some of the services data directories lack appropriate permissions for tezos user
* Automatically generated part of `postinst` script was dropped, thus serviced weren't unmasked during the package installation.
This PR fixes both aforementioned bugs.
Resolves #

[#133] Fix postinst scripts

---

Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-node-edo2net.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb

Problem: We want to create default data directories and init node
configs during the post-install stage.
Solution: Add corresponding post_install to the formulas that provide
brew services.
Currently based and targets #149 
Resolves #130 

[#130] brew formulas postinstalls

---

Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: Tezos requires rust version to be specified explicitly in case
no default suggested version (1.44.0) is used. Previously, we
depended on rust brew formulas, but the rust version in it can be
changed at any time, which means that our formulas are quite unstable.
Solution: Depend on rustup-init and fetch rust compiler via
`rustup-init --default-toolchain 1.44.0`.
Resolves None

Don't depend on rust brew formula

---

Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-sapling-params.rb
Formula/tezos-signer.rb

Problem: New release was created, brew formulas now have
tezos-sapling-params dependency and also provide background services.
We should provide an easy way to obtain updated packages without
building them from scratch.
Solution: Provide hashes for the new bottles.
Resolves #

Update bottles hashes

---

docker/package/model.py

Problem: Currently both Ubuntu and Fedora native packages target only
amd64, thus it's not possible to use our package repos on the other
architectures.
Solution: Add arm64 to the list of target architectures.
Resolves part of #157 (It'll be fully resolved only once the arm64 packages are uploaded and built)

[#157] Do native packaging for arm64

---

README.md
docker/package/model.py
docker/package/package_generator.py
docker/package/packages.py
meta.json

Problem: It would be convenient to have such aliases when it's required
to run node with the data directory specified in the systemd service
environment.
Solution: Add tezos-node-<network> scripts that are generated during
postinst stage. They are also cleaned up during the postrm.
Resolves part of #148 (it'll be closed once the updated packages are published and the baking article is updated)

[#148] tezos-node-<network> aliases

---

docker/package/scripts/tezos-accuser-start
docker/package/scripts/tezos-baker-start
docker/package/scripts/tezos-endorser-start
docker/package/scripts/tezos-node-start
docker/package/scripts/tezos-signer-start

Problem: Startup scripts currently use '#!/usr/bin/bash' shebangs.
However, some of the distros may have different bath to the bash
interpreter, thus startup script may fail on them.
Soluton: Use '#!/usr/bin/env bash' instead, so that the path to the bash
interpreter is fetched from the current environment.
Relates #162

[#162] Fix shebangs in startup scripts

---

Formula/tezos-sapling-params.rb

Problem: sha256 for tezos-sapling-params were updated, but the version
of the formula didn't, causing a brew failure in installing the
existing bottle (from the previous release).
Solution: revert the hashes in the formula for tezos-sapling-param
to match the bottles in the right release.
Resolves #166

[#166] revert bottles sha256 of tezos-sapling-params' formula

---

README.md

Problem: We'd like to have an ability to install both latest stable
version and latest release candidate brew formulas on the macOS.
However, brew tap uses master branch of the repo by default and it
cannot be changed.
Solution: Create two mirrors of the tezos-packaging repo, one mirror for
the latest stable release and one mirror for the latest release
candidate release, thus users may use one of these repos as a brew tap
and install desired stable or release candidate formulas. Mention this
capability in the README.
https://issues.serokell.io/issue/TM-535

Mention mirrored taps in the README

---

Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: Bottles for mojave and catalina were built and uploaded to the
v8.3-1 github release. These bottles now should be used in the formulas.
Solution: Update bottles hashes in the formulas.
Resolves None

Add v8.3-1 bottles hashes

---

.buildkite/pipeline.yml

Problem: Tezos v8.3 was added to the opam-repository, which means that
we can now update our native packages.
Solution: Enable package building in CI.
Resolves None

v8.3 native packages

---

Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

New v9.0 bottles have been built for brew, this adds their hashes in the formulas.
None

Update brew formula bottle hashes to v9.0

---

docs/baking.md

Problem: Providing data-dir manually to the `tezos-node` commands is a
bit inconvenient.
Solution: Suggest using tezos-node-<network> aliases instead of
providing data directory option manually.
Resolves #148 

[#148] Use new aliases in baking article

---

README.md
docs/baking.md

Problem: Now we're providing more user-friendly way to set up and
start baking instace, we should use this way in the baking doc.
Solution: Rework baking.md to use `tezos-baking-<network>` service.
~~Currently based on #164.~~ Don't merge until updated packages are published.
Relates #156

[#156] Update docs

---

Formula/tezos-accuser-008-PtEdo2Zk.rb
Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-008-PtEdo2Zk.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-008-PtEdo2Zk.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: Brew formulas have been updated to v9.1 and new bottles
are available, but their hashes are not in the formulas yet.
Solution: Update brew bottle hashes for updated formulas.
Resolves None

Update brew bottles hashes

---

.buildkite/pipeline.yml

Problem: v9.1 was released to the opam-repository, this means we can now
build native packages.
Solution: Enable native packages building in CI.
Resolves None

Build native packages in CI

---

LICENSES/LicenseRef-Apache-Ledger.txt
docker/package/model.py
docker/package/packages.py
docker/package/scripts/udev-rules

Problem: Users have to manually install udev rules in case they want to
use tezos-client along with the ledger device.
Solution: Install udev rules during post-installation stage of the
tezos-client package.
Note that potentially further changes can be required in case firmware update won't resolve an issue with the
udev rules on the Raspberry Pi.
Relates #180 (issue will be resolved once updated packages are published)

[#180] Provide ledger udev rules with tezos-client

---

docker/package/model.py
docker/package/packages.py
docker/package/scripts/tezos-baker-start
docker/package/scripts/tezos-baking-start
docker/package/scripts/tezos-endorser-start

Problem: Existing systemd services doesn't work with password-protected
keys.
Solution: Support them using systemd-ask-password.
To test locally:
```
sudo add-apt-repository ppa:rvem/tezos-experiments-1
sudo apt-get update
sudo apt-get install tezos-baking
sudo -u tezos tezos-client gen keys baker --encrypted
sudo systemctl start tezos-baking-florencenet
systemctl status tezos-baker-009-psfloren@florencenet
systemctl status tezos-endorser-009-psfloren@florencenet
sudo systemctl start tezos-node-florencenet
sudo systemctl start tezos-baker-009-psfloren
sudo systemctl start tezos-endorser-009-psfloren
systemctl status tezos-baker-009-psfloren
systemctl status tezos-endorser-009-psfloren
```
Relates #176 (issue will be resolved once updated packages are published)

[#176] Support password-protected keys

---

docker/package/packages.py
docker/package/scripts/udev-rules
meta.json

There are a bunch of problem with the existing script:
1) `udev` may be absent and thus `/etc/udev/rules.d` as well as `udevadm` won't be present
2) `udevadm` doesn't fully work inside the containers
This PR provides two fixes:
1) Packages that use udev post-installation script now depend on the `udev` package.
2) Script checks whether we're inside the container and don't add udev rules in case we're inside it.
Relates #198 (issue will be resolved once updated packages are published)

[#198] Fix ledger udev rules addition from the post-installation stage

---

.buildkite/pipeline.yml
nix/modules/common.nix
nix/modules/tezos-accuser.nix
nix/modules/tezos-baker.nix
nix/modules/tezos-endorser.nix
nix/modules/tezos-node.nix
nix/modules/tezos-signer.nix
nix/nix/sources.json
tests/tezos-modules.nix

Problem: we're providing systemd services for `tezos-node` and tezos daemons in the native packages, but there are no nixos modules for them.
Solution: added nixos modules for `tezos-node`, `tezos-signer`, `tezos-baker-<proto>`, `tezos-accuser-<proto>`, and `tezos-endorser-<proto>`.
Resolves #107 

[#107] Add nixos modules for tezos binaries

---

.buildkite/pipeline-raw.yml

Problem: 008 protocol was disabled in #200. However, CI still tries to
build native packages for 008 daemon binaries. The update from #200 was
lost in #197:(
Solution: Build 009 daemons binary packages.
Relates #195

[#195] Hotfix binary packages steps

---

docker/package/scripts/udev-rules

Problem: udev and libusb aren't fully supported in the WSL, thus an
attempt to update udev rules for a usb device fails, which leads to
inablitity of installation of our native packages.
Solution: Check if we're inside the WSL (by checking the contents of
/proc/sys/kernel/osrelease) and don't install udev rules if we're inside
it.
Relates #202  (issue will be resolved once updated packages are published)

[#202] Don't install udev rules inside WSL

---

.buildkite/filter-pipeline.py
.buildkite/pipeline-raw.yml
tests/buildkite/golden/pipeline-A.yml
tests/buildkite/golden/pipeline-C.yml
tests/buildkite/golden/pipeline-G.yml
tests/buildkite/golden/pipeline-X.yml
tests/buildkite/pipeline-raw.yml

Problem: Turned out buildkite uses 'key' attribute in order to determine
steps dependencies instead of using 'label'.
Solution: Explicitly add keys to steps that used as a dependency.
Resolves #195

[#195] Provide key attributes for dependency steps

---

docker/package/scripts/udev-rules

Problem: Ledger interaction with the udev rules provided by the packages
work only for users from the plugdev group. 'tezos' user doesn't belong
to it by default.
Solution: Add it to the required group after udev rules addition in the
post-installtion script.
Relates #210 (issue will be resolved once updated packages are published)

[#210] Add tezos user to plugdev group

---

docker/package/model.py
docker/package/package_generator.py
docker/package/ubuntu.py

Problem: Currently we support 18.04, 20.04 and 20.10. However, 21.04 was
released in the April and community lacks Tezos packages for it.
Solution: Add 21.04 (aka hirsute) to the list of supported ubuntu
versions.
Relates #212 (issue will be resolved once updated packages are published)

[#212] Ubuntu 21.04 support

---

.buildkite/pipeline-raw.yml

Problem: opam-repository was updated with 9.2 Tezos packages, which
means that we now can build native packages for Tezos.
Solution: Enable native packages building in CI again.
Resolves None

Build v9.2 native packages

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: v9.2-1 was released, brew formulas lack hashes for bottles with
precompiled binaries.
Solution: Add bottles hashes for mojave and catalina macOS versions.
Resolves None

Add v9.2 bottles hashes

---

docker/package/model.py
docker/package/tezos_baking_wizard.py

Problem: we want to have an interactive way to set up baking infrastructure, or just `tezos-node`.
Solution: created a CLI wizard to collect configuration through queries and execute the approppriate steps.
Resolves part of #201 

[#201] Add first version of baking wizard

---

docker/package/ubuntu.py
meta.json

Problem: Systemd services don't restart during the package upgrade,
thus users may miss service updates in case they didn't restart their
services manually.
Solution: Use 10 compatibility level for Ubuntu packages. In this
level services are restarted after upgrade by default. See
'--restart-after-upgrade' option description in
https://manpages.debian.org/testing/debhelper/dh_installsystemd.1.en.html.
Relates #215 (issue will be resolved once updated packages are published)

[#215] Use 10 compatibility level in ubuntu pkgs

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md

Problem: The process of creating a new release in Tezos packaging
consists of many steps and it's quite important to not miss any of them.
Since the process of creating a new release usually consist of multiple
PRs, it'll be nice to have a place where we can track the things that
was done and needs to be done in the nearest future.
Solution: Add PR template that is supposed to be used when we're
intending to create a new release. This PR will be used to track the
progress of the new release.
Resolves #226

[#226] Add PR template for releases

---

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md

Problem:
* It's non-obvious that one should build brew bottles for macOS
using macOS machine.
* Also it's non-obvious that one should comment out
native-packaging-related CI steps in case opam-repository
wasn't updated and we need to create a new release urgently.
Solution: Clarify point about bottles building and add two more points
for enabling and disabling native-packaging-related CI steps.
Resolves #226

[#226] Improve template a bit more

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb
scripts/build-bottles.sh

Problem: v9.3-1 was released, but hashes of the new bottles have not been added to the brew formulas yet.
Solution: added the bottle hashes for Mojave and Catalina macOS versions.
Also removed building the bottle for `tezos-sapling-params` from the bottle building script.
None, follows #228 

v9.3 bottle hashes

---

docker/package/tezos_baking_wizard.py

Problem: right now the Tezos Baking Wizard queries all configuration
options from the user all at once, before running the setup. This
has several undesirable ramifications, such as the inability to
re-query an option chosen by accident, or to address transient errors,
as well as asking some information unnecessarily.
Solution: updated the wizard to interleave queries and setup steps,
only asking the information when necessary and retrying failed options.
Resolves #222, resolves #219 

[#222] Modify the wizard to query between setup

---

docker/package/tezos_baking_wizard.py

Problem: Currently we show only ledger URLs for addresses that are store
on the ledgers, which is not very convenient when one has to choose the
desired key.
Solution: Also show the address that corresponds to the given URL and the
balance of this address.
Currently based on #224.
Resolves #218

[#218] Enhanced ledger interaction

---

.buildkite/pipeline-raw.yml
docker/README.md
nix/util/copr-cli.nix
nix/util/dput.nix

Problem: Currently publishing instructions for Fedora tells to upload
.src.rpm packages via Copr website. However, it's not very convenient.
Moreover, there is 'copr-cli' utility that can submit builds from the
terminal.
Solution: Update instructions to use 'copr-cli' for publishing Fedora
packages to Copr.
Resolves #231

[#231] Publish fedora packages via copr-cli

---

.buildkite/pipeline-raw.yml

Problem: we have previously disabled the CI steps having to do with
native packaging, as the opam-repository has not been updated with
the new tezos release. Now it's up-to-date again.
Solution: enable the relevant CI steps yet again.
Follows #228

Enable native-packaging back

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: v10.0-rc1-1 was released, we need to add hashes of the new
bottles to the brew formulas.
Solution: added the bottle hashes for Mojave and Catalina.
Follows #234 

Add v10.0-rc1-1 brew bottle hashes

---

docker/README.md

Problem: `Serokell/Tezos` project doesn't exist on Copr.
Solution: Use `@Serokell/Tezos` instead.
Resolves #231

[#231] Fix Copr project name

---

docker/README.md
docker/package/.dput.cf

Problem: If one is running dput not on Ubuntu, it has to provide config
to it manually.
Solution: Add a note about it to the packaging README along with the
suggested default config.
Relates #231

[#231] Add a note about dput config

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: We've built and added v9.4 bottles to the corresponding
release.
Solution: Update hashes, so that it's possible to fetch bottles for
Mojave and Catalina.
Follows #238

Add bottles hashes for v9.4 formulas

---

docker/package/tezos_baking_wizard.py

Problem: currently in the baking wizard, there's a confusing pause
in the output after importing the snapshot.
Solution: added an extra output explaining what needs to be done and
what has already transpired. Removed the message repeating every second.
Resolves #243 

[#243] Improve progress reporting in baking wizard

---

.buildkite/pipeline-raw.yml
docker/README.md

Problem: opam-repository was updated with the v9.4 Tezos packages.
Solution: Enable native packages building in CI.
Follow #238

v9.4 native packages

---

docker/package/tezos_baking_wizard.py

Problem: 'tezos-client setup ledger to baker' doesn't update high
watermark by default and thus bakes and endorsements can be missed in
case we switch from a network with higher number of blocks to the network
with lower number of blocks.
Solution: Provide current level as high watermark explicitly.
Resolves #244 

[#244] Set high watermark explicitly

---

.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
docker/package/model.py
docker/package/tezos_setup_wizard.py

Problem: the CLI wizard we provide can be used to set up a baking
instance or just the Tezos node, but we call it `tezos-baking-wizard`.
This name is a bit confusing.
Solution: renamed the wizard to `tezos-setup-wizard`.
Resolves part of #201 

[#201] Rename the CLI wizard

---

README.md
docs/baking.md

Problem: we have added a CLI setup wizard for tezos baking, but there
is no mention of it in the documentation.
Solution: update README.md and the baking guide for Ubuntu to mention
the wizard and how to use it. Additionally, fix and/or update some places
in the baking guide with new information about supported protocols and workflow.
Resolves #201 

[#201] Update README and the baking guide

---

README.md
docs/distros/fedora.md
docs/distros/macos.md
docs/distros/ubuntu.md
docs/systemd.md

Problem: At the moment main README.md is quite large and it's hard to
navigate through it, even though it has a table of contents.
Usually, users are interested in only one way of distribution and it's
not convenient for them to skim through the other distribution options.
Solution: Split README into multiple docs:
* README itself that points to the other docs.
* Ubuntu-related instructions.
* Fedora-related instructions.
* macOS-related instructions.
* Doc about systemd services.
* Doc about launchd services.
Resolves #251

[#251] Reorganize readme

---

README.md

Problem: There are some ambiguous anchors that make crossref-verify
unhappy.
Solution: Remove them and use automatically generated anchors instead.
Fixup for #251

[#251] Fix ambiguous anchors in the README

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: v10.0-rc2 bottles have been built and added to the latest release.
Solution: added hashes for Mojave and Catalina to brew formulae.
Follows #261 

Add bottle hashes for v10.0-rc2

---

nix/nix/sources.json

Problem: PR in opam-nix was finally merged and now we can use its stable
version.
Solution: Use stable version of opam-nix from master branch.
Resolves None

Use stable opam-nix

---

docker/package/model.py
docker/package/packages.py
meta.json

Problem: granada will be activated on mainnet very soon. We need to support an automatic switchover.
Solution: added `010-PtGRANAD` to the list of mainnet protocols.
Resolves #

Granada mainnet activation

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: Bottles for v9.5 was built and added to the latest release, but
formulae lack their hashes.
Solution: Add hashes for Mojave and Catalina bottles to them.
Follows #266

Add bottles hashes for v9.5

---

release.nix

Problem: http://keys.gnupg.net/ seems to be dead. As a result users
cannot import the key and check releases artifacts.
Solution: Push key to a bunch of key servers and point to a working one
in the release message.
Resolves #267

[#267] Change suggested keyserver for checking

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node-florencenet.rb
Formula/tezos-node-granadanet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
Formula/tezos-signer.rb
nix/nix/sources.json

This PR introduces a new 9.7 release in tezos-packaging.
The opam-repository revision should be the same as the one defined in
[`tezos/tezos`](https://gitlab.com/tezos/tezos/-/blob/master/scripts/version.sh) for the relevant tag.

9.7 release

---

Formula/tezos-accuser-009-PsFLoren.rb
Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-009-PsFLoren.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-009-PsFLoren.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: v9.7 bottles have been built and added to the latest release, but their hashes are not yet in the formulae.
Solution: added hashes for Mojave and Catalina to brew formulae.
Follows #271 

Add brew bottle hashes for v9.7

---

.buildkite/pipeline-raw.yml
.github/workflows/build-bottles.yml
.github/workflows/check-formulas.yml

Replaces buildkite step for checking homebrew formulas with a Github Actions workflow, and adds another workflow to build and export bottles using catalina runners provided by github. Github does not provide mojave runners, so for mojave we'll still have to build bottles ourselves. And the bottles are only built on master branch because it takes a long time, but here's an example of the workflow running: https://github.com/serokell/tezos-packaging/runs/3260140954.
The bottles are exported as a workflow artifact and can be downloaded from the workflow page. It would be nice to attach them to the pre-release automatically, but I don't know if there is a simple way to do it, because releases are created from buildkite, and buildkite attaches some of its artifacts as well, so we can't really …

Use Github Actions for checking and building homebrew bottles

---

Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node-granadanet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
Formula/tezos-signer.rb
nix/nix/sources.json

This PR introduces a new  release in tezos-packaging.
Follows #
The opam-repository revision should be the same as the one defined in
[`tezos/tezos`](https://gitlab.com/tezos/tezos/-/blob/master/scripts/version.sh) for the relevant tag.

v10.0 release

---

docker/package/packages.py
docker/package/scripts/tezos-node-prestart

Problem: 9.* to 10.* upgrade requires a storage upgrade.
We want to automate this upgrade process.
Solution: Check the current storage version in the node service pre-start
script and perform an upgrade in case it's needed.
Relates #291 (will be resolved, once corresponding updated package is published)

[#291] Automatic update node storage

---

Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: v10.1 bottles have been built and added to the latest release, but their hashes are not yet in the formulae.
Solution: added hashes for Mojave and Catalina to brew formulae.
Follows #294

Add brew bottle hashes for v10.1

---

.buildkite/pipeline-for-tags.yml
.github/workflows/build-bottles.yml

Problem: we build homebrew bottles for catalina in CI, but not for mojave. And the bottles have to be attached to the releases manually.
Solution: add buildkite pipeline which builds mojave bottles when a tag is pushed, and add automatic attachment for both catalina and mojave.
In buildkite it's a separate pipeline `tezos-packaging-tags`, which runs when a tag is pushed rather than a branch, it takes jobs from `.buildkite/pipeline-for-tags.yml` file.
Resolves #285

[#285] Build mojave bottles and attach bottles to releases in CI

---

.buildkite/pipeline-raw.yml
scripts/bottle-hashes.sh
tests/bottle-hashes/test-hash-insert.sh

Problem: every time after a new release, we build brew bottles,
and their SHA256 hashes should be added to the brew formulae.
Right now we do this manually, but it's a tedious and error-prone
process that would be nice to automate.
Solution: added a bash script that can do this. It takes a directory
where the bottle.tar.gz files are placed as its argument and inserts
the computed hash for the respective OS into the right formula.
It is supposed to be run from the base directory (tezos-packaging).
Resolves #284 

[#284] Add script automating bottle hash insertion

---

Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node-granadanet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
Formula/tezos-signer.rb
nix/nix/sources.json

This PR introduces a new v10.2 release in tezos-packaging.
Follows #
The opam-repository revision should be the same as the one defined in
[`tezos/tezos`](https://gitlab.com/tezos/tezos/-/blob/master/scripts/version.sh) for the relevant tag.

v10.2 release

---

Formula/tezos-accuser-010-PtGRANAD.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-010-PtGRANAD.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-010-PtGRANAD.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: v10.2 bottles have been built and added to the latest release,
but their hashes are not yet in the formulae.
Solution: added hashes for Mojave and Catalina to brew formulae.
Follows #298

Add brew bottle hashes for v10.2

---

nix/nix/sources.json
nix/nix/sources.nix
scripts/shell.nix

Bump nix dependencies, to keep them up to date.
We repinned to upstream nixpkgs long time ago because of some bug in nixpkgs, but it's been fixed since then, I repinned it back to our fork.
Related issue: https://issues.serokell.io/issue/OPS-1269

Bump nix dependencies

---

nix/build/hacks.nix
protocols.json

Problem: Alpha protocol is now required to run 'tezos-client' in mockup
mode.
Solution: Allow it and adjust hacks.nix.
https://gitlab.com/morley-framework/morley/-/issues/664

[morley#664] Allow alpha protocol

---

.buildkite/pipeline-for-tags.yml
.github/workflows/build-bottles.yml
scripts/bottle-hashes.sh
scripts/shell.nix
scripts/sync-bottle-hashes.sh
scripts/update-brew-formulae.sh

Problem: we need to automate brew bottles-related processes further.
Right now we automatically build and attach the bottles to releases, and we have a script that computes and inserts their hashes to the respective formulae.
It's a natural next step to open the PRs from the CI.
Solution: added a step to each pipeline that should sync the hashes in a common branch, and then open a PR automatically.
Resolves #286 

[#286] Automate bottle hashes PR

---

docker/README.md
docker/package/.dput.cf
docs/baking.md
docs/distros/fedora.md
docs/distros/ubuntu.md

Problem: Native Ubuntu and Fedora packages that we provide no longer
depend on opam-repository and depend only on the upstream repository,
thus we're now able to publish native packages for release-candidate
releases as well.
Solution: Corresponding PPA and Copr project were created, instructions
were updated to mention them in the publishing instructions.
https://issues.serokell.io/issue/TM-536

Release candidate packages publishing instruction

---

docs/baking.md

The URL in the baking doc instruction's command to use the PPA for release candidates, is incorrect.
This small fixup corrects it.
None

[Chore] Fix URL for Ubuntu's RCs PPA in docs

---

.buildkite/pipeline-for-tags.yml
nix/nix/sources.json
scripts/shell.nix
scripts/update-brew-formulae.sh
scripts/update-tezos.sh

This PR adds a script that checks if Tezos upstream had a new release and creates
a new PR with basic changes required for the new release.
This script is supposed to be run on schedule with some interval which is TBD.
A test PR created by the CI: https://github.com/serokell/tezos-packaging/pull/311
Resolves #288

[#288] Automatic upstream updates

---

Formula/tezos-accuser-011-PtHangz2.rb
Formula/tezos-baker-011-PtHangz2.rb
Formula/tezos-endorser-011-PtHangz2.rb

Problem: class names in brew formulae for hangzhou don't match
their respective filenames.
Solution: fix up the class names.
Related to #324

[Chore] fix hangzhou-specific class names in brew formulae

---

.buildkite/filter-pipeline.py
tests/buildkite/golden/pipeline-A.yml
tests/buildkite/golden/pipeline-C.yml
tests/buildkite/golden/pipeline-G.yml
tests/buildkite/golden/pipeline-X.yml
tests/buildkite/pipeline-raw.yml

Problem: Currently filter-pipeline.py will fail in case a pipeline
the configuration has non-dict steps, e.g. 'wait'.
Solution: Ignore non-dict steps in pipeline-filtering and don't skip
them in the resulting pipeline.
Resolves #332

[#332] Handle non-dict steps in pipeline filtering

---

.buildkite/pipeline-raw.yml
scripts/autorelease.sh

Problem: we have automated almost the whole release making process except for actually publishing the release from autoreleases. Currently, after the release PR is merged and a auto pre-release made, we have to manually push a tag and publish a release with a correct name.
This has already lead to maintainers forgetting to publish a release, which led to some CI issues. We would like to mitigate this by automating this process as well.
Solution: reworked the auto-release making process to actually make full releases/pre-releases if we merged a release PR, or still make an `auto-release` if not.
Resolves #334 

[#334] Auto create release upon release PR merge

---

.buildkite/pipeline-raw.yml
scripts/sign-commits.sh
scripts/sync-bottle-hashes.sh
scripts/update-tezos.sh

Problem: Public github actions runners don't have access to our signing
key, thus it's impossible to sign commits before pushing.
Solution: Sign commits in a separate CI step that will be triggered when
the branch with formulae update is updated. The script in this step will
sign all commits from current branch and 'git push
--force-with-lease' signatures.
Fix to a bug that was introduced in a4241488bfd54bdf7021cae4ef1de91f56474650.
Resolves None

[Chore] Don't sign commits in bottles sync script 

---

.github/release_pull_request_template.md

We have already mostly refactored the release PR template, but the two remaining automation issues (#314 and #334) were since then closed, so we need to remove those steps from the template as well.
Relates to #328 

[#328] Re-update the release PR template

---

.buildkite/pipeline-raw.yml

Problem: in a CI run after merging a release PR, updating the relevant mirror repo fails because we don't use the proper `--mirror` option.
Solution: added the flag to the commands.
Resolves #314

[#314] Fix 'not on branch' error on updating mirrors

---

.buildkite/pipeline-raw.yml
scripts/sign-commits.sh
scripts/sync-bottle-hashes.sh

Problem: It has an outdated <unsigned> suffix that is a leftover from one
of the !327 versions.
Solution: Remove this suffix from the PR header.
Resolves None

[Chore] Fix bottles' hashes PR header

---

Formula/tezos-sandbox.rb

Problem: there is a known issue with using tezos-sandbox on MacOS, which is that it depends on `coreutils` and `util-linux`. These are not installed upon running `brew install tezos-sandbox`.
Additionally, homebrew installs all tools that conflict with MacOS ones in name with the `g` prefix, meaning the user needs to manipulate `$PATH` to use these dependencies.
Solution: added `coreutils` and `util-linux` as dependencies to the `tezos-sandbox` formula. As brew does not allow for post-setup user configuration manipulation, `$PATH` cannot be easily modified to include `gnubin`. We use the paradigmatic homebrew way and output the command in the caveats section for the user to run manually.
Resolves #323 

[#323] Add dependencies to tezos-sandbox formula

---

Formula/tezos-accuser-011-PtHangz2.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-011-PtHangz2.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-011-PtHangz2.rb
Formula/tezos-node-hangzhounet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
Formula/tezos-signer.rb
meta.json

Problem: Currently formulae download opam x86_64 binary from the
GitHub release, which causes a build failure on machines with M1 CPU.
Solution: Determine CPU architecture in runtime and download appropriate
opam binary.
Relates #205 (will be resolved once mirror repository is updated)
Resolves #354 (documentation update won't be needed since we're going to support M1 natively)

[#205] Provide M1 support

---

.github/workflows/build-bottles.yml
Formula/tezos-sapling-params.rb
scripts/bottle-hashes.sh
scripts/sync-bottle-hashes.sh
scripts/update-brew-formulae.sh

Problem: At the moment we provide bottles only for Mojave and Catalina,
and both of these versions are quite old at the moment. Service support
for Mojave stopped some time ago.
Solution: Build bottles for x86_64 Big Sur using GitHub actions since
they recently started providing runners with this macOS version.
You can check [this pipeline](https://github.com/serokell/tezos-packaging/runs/4561166171) to ensure that it actually works.
Resolves first part of #353. `arm64` support will be provided in another PR.

[#353] Big Sur GitHub actions

---

.buildkite/pipeline-for-tags.yml
Formula/tezos-sapling-params.rb
scripts/bottle-hashes.sh
scripts/update-brew-formulae.sh

Problem: Since Big Sur, macOS targets two different architectures:
x86_64 and arm64. Each architecture requires its own bottle with
a prebuilt binary.
Currently, our CI setup lacks arm64 Big Sur bottles building.
Solution: Use buildkite-agent that is running on M1 mac for building
arm64 bottles. Also, attach these bottles to the releases and provide
their hashes to the formulae automatically.
Resolves #353

[#353] arm64 Big Sur bottles building in CI

---

README.md
docs/versioning.md

Problem: Our versioning policy isn't documented anywhere, as a result
users may get confused when they see a package with a version that is
different from the upstream release version.
Solution: Write a doc that explains our versioning policy and the way in
which packages for upstream releases and pre-releases are distributed.
Also, refer to this doc in the main README.
Resolves #346

[#346] Document versioning policy

---

docker/package/model.py
meta.json

Problem: There is no endorser daemon in 012 protocol. However,
'tezos-baking' package ended up depending on 'tezos-endorser-012-psithaca'.
As a result, it's impossible to install/upgrade tezos-baking-12.0-rc1-0ubuntu1 :(
Solution: Remove dependency on 'tezos-endorser-012-psithaca' package.
Resolves a bug introduced in #360.

[Chore] Fix tezos-baking package dependencies 

---

tests/test_script.py

Problem: Sometimes binaries tests are failing due to the inability to clean
up node data directory.
Solution: Clean up may fail in case node didn't shut down completely
before removing the data directory.
Wait for the node process to die before the data directory removal.
Resolves #339

[#339] Wait for node to shutdown before cleaning

---

docker/package/tezos_setup_wizard.py
docs/baking.md

Problem: There are several occurencies of https://faucet.tzalpha.net/,
which is deprecated since hangzhounet and doesn't work now.
Solution: Replace them with https://teztnets.xyz/.
Resolves #

[Chore] Fix faucet link

---

Formula/tezos-node-ithacanet.rb

Problem: tezos-node-ithacanet.rb main class has invalid name. As a
result, an attempt to tap serokell/tezos-packaging-rc results in an
error.
Solution: Fix the class name to match the formula name.
Resolves None

[Chore] Fix tezos-node-ithacanet formula class name

---

README.md
docker/package/scripts/udev-rules
docs/distros/ubuntu.md
docs/systemd.md

Problem: During testing it was found that `tezos-packaging`
can be used on WSL, but its usage has some limitations.
Solution: Information about WSL support was added to support
policy doc. Limitations are also mentioned in the corresponding
sections.
Resolves #375

[#375] Document 'tezos-packaging' usage on WSL

---

docker/package/model.py
docker/package/tezos_setup_wizard.py
docker/package/tezos_voting_wizard.py
docker/package/wizard_structure.py
docs/tests/voting.md

Problem: bakers who want to vote on the Tezos protocol amendment currently have to do it through base `tezos-client` or other unintuitive avenues. As we already have an interactive baking setup wizard, we would like to extend interactive capabilities of our packages and provide a similar wizard for voting.
Solution: added the first version of Tezos Voting Wizard.
Resolves #237 

[#237] Create the first version of a voting wizard

---

docker/package/model.py
docker/package/package_generator.py
docs/support-policy.md

Update list of supported OSes versions:
1) Remove Ubuntu 21.04 since it's obsolete now.
2) Mention that there are both `x86_64` and `aarch64` packages for Fedora 35 now.
Resolves #390

[#390] Update support policy doc

---

.buildkite/pipeline-raw.yml

Problem: 'git push --mirror' pushes changes from the local ref which is
nearly empty due to the way buildkite fetches repository before doing
CI step.
Solution: Explicitly fetch, checkout, and pull current branch before
pushing to the mirror repository.
Resolves #

[Chore] Fetch BUILDKITE_BRANCH before updating mirror

---

Formula/tezos-node-hangzhounet.rb
Formula/tezos-node-ithacanet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
docs/distros/macos.md
scripts/build-one-bottle.sh

In several brew meta formulae we use the `bottle :unneeded` option, that has been deprecated and recently removed entirely.
This PR removes this option from the affected formulae.
Resolves #398

[#398] Remove unneeded bottle field for meta brew formulae

---

docker/README.md
docker/package/fedora.py

Problem: COPR reports tezos-baking-v12.0-1 failing to build on any
version/architecture because 'tezos-baking-custom@.default' isn't found.
Solution: fixed the bug in how the default name is chosen.
Relates to #369 

[Chore] Fix: tezos-baking fails to build on Fedora

---

docs/baking.md
docs/distros/ubuntu.md

Recently the 64bit version of the Raspberry Pi OS [has been made more visible and easily available](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/) and the current version is also based on a newer release of Debian.
This PR updates the documentation to reflect these news.
None

[Chore] Update installation instruction for new Raspberry Pi OS

---

docker/package/packages.py
meta.json

Problem: Ithaca will soon be activated on mainnet. We need to support
an automatic switchover.
Solution: added 012-Psithaca to the list of mainnet protocols.
None

[Chore] Ithaca mainnet activation

---

docs/versioning.md

This PR clarifies in the docs that not all packaging `<releases>` will result in an update of all packages across all distributions.
Additionally it fixes some typos in the versioning doc.
None

[Chore] Add some more docs on packaging release numbers

---

.buildkite/generate-tags-pipeline.sh
.github/workflows/build-bottles.yml
scripts/check-bottle-built.sh

Problem: currently, both on GitHub Actions and with Buildkite, we build brew bottles on a new tag being pushed. In these runs, the bottle-building CI steps that have to do with:
1. checking that the bottle has already been built;
2. attaching built bottles to releases;
3. making commits that add new hashes to the formulae;
use the tag that triggered the pipeline. Turns out this behaviour doesn't work for any subsequent releases we make in the same upstream release, because the bottle versions usually stay the same, leading e.g. to the `v.*-2` release having `v.*-1` bottles attached.
Solution: changed the scripts to use the version of a specific formula where appropriate, or the one in `tezos-client.rb` where there is no specific bottle to be handled, as `tezos-client` is probably going to …

[#409] Use formulae tags for attaching bottles to releases

---

Formula/tezos-accuser-011-PtHangz2.rb
Formula/tezos-accuser-012-Psithaca.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-011-PtHangz2.rb
Formula/tezos-baker-012-Psithaca.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-011-PtHangz2.rb
Formula/tezos-node-hangzhounet.rb
Formula/tezos-node-ithacanet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
Formula/tezos-signer.rb
docker/build/build-tezos.sh
docker/package/model.py
meta.json

Problem: By default ocaml-bls12-381 library (which is used as a
dependency by Octez) is compiled using instructions from ADX extension.
As a result, if package was build on a CPU that has this extension, CPUs
that don't have it won't be able to use binary from this package.
Solution: Compile Octez with 'BLST_PORTABLE=y' to avoid using ADX
instruction in ocaml-bls12-381.
We still need to find a way to test built packages and binaries on old CPU.
Relates #414 (will be resolved once updated packages are released).

[#414] Compile ocaml-bls12-381 without ADX extension

---

.buildkite/generate-tags-pipeline.sh
.github/workflows/build-bottles.yml

Problem: At the moment, we use GitHub actions in order to build x86_64
Big Sur bottles. However, now we have our own infrastructure based on
Big Sur can be used to build x86_64 bottles using Rosetta.
Solution: Now we have an additional buildkite agent that runs all command
under Rosetta and have access to x86_64 brew binary.
Update 'generate-tags-pipeline.sh' script to generate steps
for building x86_64 Big Sur bottles using this new buildkite agent.
https://issues.serokell.io/issue/TM-609

Use self hosted x86 Big Sur builder

---

scripts/check-bottle-built.sh

Problem: This script returns 1 exit code in case grep fails due to
'set -e'.
Solution: Allow 'gh release view ... | grep ...' to fail by setting
'set +e' before it.
Relates #409

[Chore] Hotfix 'check-bottle-built.sh'

---

.buildkite/generate-tags-pipeline.sh
.github/workflows/build-bottles.yml

1) Fix `FORMULA_TAG` variable handling in BK tags pipeline.
2) Add `GITHUB_TOKEN` variable to `Add bottle hashes to formulae` step on GA to allow
it to open PRs.
Resolves #

[Chore] More hotfixes to the bottles release proccess

---

Formula/tezos-accuser-011-PtHangz2.rb
Formula/tezos-accuser-012-Psithaca.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-011-PtHangz2.rb
Formula/tezos-baker-012-Psithaca.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-endorser-011-PtHangz2.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: we have built brew bottles for the new Octez release, but their hashes
aren't in the formulae yet.
Solution: added the hashes.

[Chore] Add bottle hashes for v12.0-3

---

.buildkite/pipeline-raw.yml

Problem: 'MIRROR_REPO' is a runtime step variable. As a result
'$MIRROR_REPO' interpolation returns an empty string, see
https://buildkite.com/docs/pipelines/environment-variables#runtime-variable-interpolation.
Solution: Escape '$' character.
Resolves #

[Chore] Fix 'MIRROR_REPO' variable interpolation

---

docs/baking.md
docs/systemd.md

Problem: Protocol switch-over requires users to run two sets of daemons.
Our baking doc should mention how `tezos-baking` services handle it.
Solution: Add a section to the baking doc which mentions that
`tezos-baking` package handles this requirement.
Also, fix `gen_systemd_service_file.py` usage instructions
Relates #421

[#421] Protocol switch-over with 'tezos-baking'

---

.buildkite/generate-tags-pipeline.sh

Problem: Currently this step depends on non-architecture specific
step 'uninstall-tsp' which is no longer present.
Solution: Make it depend on arch-specific uninstall-tsp steps.
Resolves #

[Chore] Fix 'Attach bottles to the release' dependencies

---

docker/package/tezos_voting_wizard.py
docker/package/wizard_structure.py
docs/voting.md

Problem: currently, Tezos Voting Wizard will ask to choose the network
to vote on first thing upon startup. This introduces an extra step
unnecessary for the vast majority of users, who will only ever want
to vote on mainnet.
Solution: removed the two steps meant to find out the network, replaced
them with a command line argument that defaults to 'mainnet'.
Resolves #402 

[#402] Get network for voting from CL arguments

---

docs/distros/macos.md

Problem: 'HOMEBREW_PREFIX' has changed on Macs with Apple CPUs. As a
result, Octez binaries are unable to find zcash-params installed by
'tezos-sapling-params' formula.
Solution: It's impossible to fix this issue properly from the brew formula
side. So we document a workaround instead. Additionally, we've
submitted a patch to the upstream that targets to resolve this issue
and it is hopefully going to be included in the next release.
Relates #385

[#385] Document workaround for zcash-params on M1 Macs

---

docker/package/packages.py

Problem: ithaca has been activated on mainnet, so there is no
longer need to run its daemons in the mainnet baking service.
Solution: Remove hangzhou from the mainnet baking service.
None

[Chore] Remove hangzhou from mainnet baking service

---

docker/package/tezos_setup_wizard.py
docker/package/tezos_voting_wizard.py
docker/package/wizard_structure.py

Problem: currently, the voting wizard only supports systems which
have baking through systemd services set up. This is not the actual
minimal requirement, which is access to a ledger via tezos-client.
Solution: only check the service for baking info if it's running,
otherwise collect the necessary information from the user.
Resolves #401

[#401] Don't require tezos-baking-mainnet.service to vote

---

docker/package/tezos_setup_wizard.py
docker/package/tezos_voting_wizard.py
docker/package/wizard_structure.py
docs/voting.md

Problem: Currently the voting wizard supports mainnet and custom networks, but not testnets.
Solution: Add support for the testnets.
Resolves #442 

[#442] Support testnets in the voting wizards

---

docker/package/tezos_setup_wizard.py
docker/package/tezos_voting_wizard.py
docker/package/wizard_structure.py
docs/tests/voting.md

Problem: there are several minor inconveniences affecting both Tezos
wizards: the URL validator sometimes fails to report an issue correctly,
and it's not possible to go back after choosing ledger as your key import
method to choose another one without closing the whole wizard.
Solution: changed the URL joining method, added an out to waiting for the
ledger app.
Follows #433

[#401] Fix URLs and waiting for ledger

---

Formula/tezos-baker-013-PtJakart.rb

Problem: The startup script for 'tezos-baker-013-PtJakart.rb' is written to
non-existing path. This causes build to fail.
Solution: Fix startup script path.
Resolves #

[Chore] Fixup tezos-baker-013-PtJakart.rb

---

Formula/tezos-accuser-012-Psithaca.rb
Formula/tezos-accuser-013-PtJakart.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-012-Psithaca.rb
Formula/tezos-baker-013-PtJakart.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-node-ithacanet.rb
Formula/tezos-node-jakartanet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
Formula/tezos-signer.rb
docker/package/model.py
docker/package/packages.py
meta.json
scripts/update-tezos.sh

Problem: 'tezos-node' fails with 'Failure "resolution failed: unknown scheme"'
inside fresh Ubuntu docker container when it attempts to resolve some URL.
Solution: Add 'netbase' dependency to Ubuntu 'tezos-node' package.
Relates #451

[#451] Add 'netbase' to 'tezos-node' package deps

---

docker/README.md
docker/package/model.py
docker/package/package_generator.py
docs/support-policy.md

Problem: Ubuntu 22.04 was released recently. We should provide packages for it.
Solution: Provide support for it.
Resolves #444

[#444] Support Ubuntu 22.04

---

docker/package/scripts/tezos-baker-start

If node needs more time to start responding, than baker/endorser services can wait for it, systemd restarts all the tezos services indefinetily.
Resolves #403

[#403] Services fail to start

---

Formula/tezos-accuser-012-Psithaca.rb
Formula/tezos-accuser-013-PtJakart.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-012-Psithaca.rb
Formula/tezos-baker-013-PtJakart.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-node.rb
Formula/tezos-sandbox.rb
Formula/tezos-signer.rb

Problem: we have built brew bottles for the new Octez release, but their hashes
aren't in the formulae yet.
Solution: added the hashes.

[Chore] Add bottle hashes for v13.0-1

---

docs/distros/macos.md

Problem: 'tezos-node' is now capable of searching 'zcash-params' within
HOMEBREW_PREFIX. However, docs still mention that additional workaround
is needed on macs with Apple CPUs.
Solution: Remove this workaround from macos-related doc.
Resolves #

[#385] Remove 'zcash-params' workaround from macos doc

---

.buildkite/check-trailing-whitespace.sh
.buildkite/pipeline-raw.yml
docker/package/scripts/build-binary.sh
scripts/build-one-bottle.sh
scripts/check-bottle-built.sh
scripts/update-tezos.sh

Problem: We have some linters running on our Buildkite pipeline.
However, we don't check shell scripts in any specialised way.
It would be nice to add shellcheck to run on every .sh file.
Solution: Add CI step for bash scripts linting and fix existing
style problems.
Resolves #462 

[#462] Add shellcheck linter to CI

---

docker/package/scripts/build-binary.sh

Problem: After recently applied shellcheck suggestions,
'build-binary.sh' doesn't provide a list of opam files to install
correctly.
Solution: Store find result in the array instead of a single string
variable to provide proper quoted expansion.
Resolves #

[Chore] Hotfix 'build-binary.sh' script

---

README.md
docs/distros/ubuntu.md
docs/support-policy.md

Problem: We should be able to use serokell launchpad ppa
on some debian releases, but straightforward way won't work
because of different versioning policies.
Solution: Provide commands to install on debian and update docs.
Resolves #438 

[#438] Document PPA installation steps on Debian

---

docker/package/Dockerfile-fedora
docker/package/Dockerfile-ubuntu
docker/package/fedora.py
docker/package/model.py
docker/package/tezos_setup_wizard.py
docker/package/tezos_voting_wizard.py
docker/package/ubuntu.py

Problem: Right now, when installing the tezos-baking package, we just
copy this common file to /usr/bin/ together with the wizards'
executable scripts.
Solution: Change the buildsystem to pybuild.
Resolves #388

[#388] Properly package two wizards

---

docker/package/tezos_setup_wizard.py

Problem: When Ctrl+C is fired during the step that interacts with
the ledger during baker setup wizard fails with an error.
Solution: Handle the exception.
Resolves #472 

[#472] Handle ledger setup interruption

---

.buildkite/pipeline-raw.yml
nix/nix/sources.json

Problem: opam-repository currently pinned to branch that no longer
exists.
Solution: Repin it to master.
Resolves #

[Chore] Repin opam-repository branch

---

docker/package/model.py
meta.json

Problem: On updating (or installing) tezos-baking's latest version
a message is printed about the liquidity toggle vote option that is
mandatory since jakarta, but this does not tell the user what needs
to be done nor how.
Solution: Improve the update message by making it stand out more and
adding info about the default value and using tezos-setup-wizard to
change this option.
Resolves #484

[#484] Improve the update message about liquidity toggle vote 

---

scripts/bottle-hashes.sh

Problem: GA tend to create a PR with bottles hashes updates
even though formulae already have these hashes.
Solution: Check if the formula already has the hash of the given bottle
before updating it.
Resolves #486

[#486] Avoid unnecessary formulae bottles hashes' updates

---

docker/README.md
docker/docker-tezos-packages.sh
docker/package/fedora.py
docker/package/model.py
docker/package/package_generator.py
docker/package/packages.py
docker/package/ubuntu.py

Currently there is no option to use pre-built static binaries on the Debian/Fedora packages. Creating the packages will always involve building from scratch. This might not be desirable when there is another CI process that builds the binaries.
None

Add option to create packages from pre-built static binaries

---

docker/package/tezos_setup_wizard.py

Problem: Currently setup wizard attempts to call 'setup ledger to bake
for' for every key type. As a result, an attempt to setup remote or
secret-key baker fails with an error.
Solution: Call this function only when the selected key type is ledger.
Resolves #491 

[#491] 'setup ledger to bake for' only for ledger key

---

docker/package/model.py
meta.json

Problem: We'd like to release packages with the recent changes that
include Ithaca support removal and fix to the setup wizard.
Solution: Bump release number and 'tezos-baking' package letter version,
so that it's possible to release new packages.
Resolves #

[Chore] Bump release number and 'tezos-baking' letter version

---

.github/workflows/build-bottles.yml
scripts/bottle-hashes.sh
scripts/sync-bottle-hashes.sh
tests/bottle-hashes/test-hash-insert.sh

Problem: In some cases bottles' hashes are updated even when current
release hasn't updated any formulae.
Solution: Assert that the formula version as the same as current tag
before updating bottle hash.
I've tested the changes with `v13.0-test` tag, CI refused to push any changes:
* https://github.com/serokell/tezos-packaging/runs/7250322868
* https://buildkite.com/serokell/tezos-packaging-tags/builds/1887
Resolves #486

[#486] Ensure formula have the same version as current tag to update bottle

---

.buildkite/pipeline-raw.yml
default.nix
flake.lock
flake.nix
nix/build/zcash.nix
release.nix
scripts/autorelease.sh
scripts/build-all-bottles.sh
scripts/publish-native-packages.sh
scripts/update-tezos.sh
shell.nix
tests/tezos-binaries.nix

Problem: release derivation wasn't built due to incorrect
flake output declaration.
Solution: Get rid of misleading flake-utils functions.
Resolves #

[Chore] autorelease.sh hotfix

---

docker/package/meta.py
docker/package/model.py

We add the option to specify the LICENSE version we're fetching during the build to support package verisons that are not also git tags on the repo.
None

Add ability to override the license version

---

.github/workflows/check-formulas.yml
scripts/build-all-bottles.sh

Problem: 014 Daemons weren't included into the list of formulae that are
build via BK.
Solution: Extend the list with 014 daemons.
Resolves #

[Chore] Include 014 daemons to formulae build list

---

docker/package/Dockerfile-ubuntu
docker/package/model.py
docker/package/packages.py
docker/package/patches/build-binary.sh.patch
docker/package/patches/build-binary.sh.patch.license
docker/package/scripts/build-binary.sh
docker/package/ubuntu.py
meta.json

Problem: Native packages cannot be built on Launchpad due to the fact
build consumes too much disk space because of excessively copied Octez
sources. Also, in the latest release, all packages '.opam' files were
moved to a dedicated directory.
Solution:
1) Avoid installing packages during opam switch creation.
2) Add 'opam' directory to the list in which opam files are searched.
Also, provide a way to propagate this fix to the existing packages via patch file.
Resolves #

[Chore] Fix 'build-binary.sh' script

---

.github/workflows/build-bottles.yml
docs/support-policy.md
scripts/bottle-hashes.sh
scripts/update-brew-formulae.sh
tests/bottle-hashes/test-hash-insert.sh

Problem: GA no longer provide runners with Catalina and thus we're
unable to build bottles for Catalina automatically due to lack of
infrastructure.
Solution: Build bottles for `x86` Monterey instead of Catalina since GA
provide such runners. Also, update support policy doc to reflect the
changes.
Resolves #508

[#508] Use Monterey runners in GA instead of Catalina

---

scripts/autorelease.sh

Problem: in the autorelease.sh script the interpolation of an empty
variable results in two consecutive spaces, which is incorrectly
interpreted as an empty argument by the 'gh' command.
Solution: remove the double quotes to solve the issue and add a
shellcheck ignore to avoid marking this as incorrect.
Note: this partially reverts d7732417d282196f55cc5847b6f4d8dd466c9781
For reference:
1. [recent occurrence of the issue](https://buildkite.com/serokell/tezos-packaging/builds/2886#01825a14-28ca-49f2-b90f-c41c63e2b706)
2. [proof of `gh` failing because of an empty `mode_flag`](https://buildkite.com/serokell/tezos-packaging/builds/2911#01825ecc-a4ef-4c5e-ac18-19924b1b4bb6)
3. [proof of `gh` working as expected without `mode_flag`](https://buildkite.com/serokell/tezos-packaging/builds/2910#018 …

[Chore] Fix interpolation bug in autorelease.sh

---

.buildkite/pipeline-for-tags.yml
scripts/build-all-bottles.sh

Problem: currently in case a bottle fails to be built, or uploaded,
an error message is printed, but the exit code remains 0.
This is a problem because one can miss this easily in the logs
and also because the successful step cannot be retried on CI.
Solution: return a non-0 exit code when any of the bottles failed to
build or was not uploaded.
Additionally add automated retries of the bottle building steps in CI.
Related to #418 (see last point in acceptance criteria)

[Chore] Fail in CI when bottles were not built or uploaded

---

release.nix

Problem: currently the 'commonMeta.version' as defined in
tezos-release.nix will drop the initial "v" from the 'branchName'
only when this starts with "refs/tags/", but in some cases this
part is missing.
Solution: modify the definition to drop the initial "v" whether
or not there is a "refs/tags/" at the start of the 'branchName'.
None

[Chore] Always remove the initial 'v' from commonMeta.version

---

docker/package/fedora.py

Problem: Fedora package systemd unit systemd env file
name was lowercased during packaging, which caused
failure to start corresponding service.
Solution: Don't lowercase env file name in fedora packaging.
Resolves #

[Chore] Fix fedora packaging

---

docker/package/model.py

Problem: Liquidity baking voting toggle is mandatory since v13.0 and
it shouldn't be new anymore for users. However, we'll still notify about
the necessity to change the vote from default on each 'tezos-baking'
package installation/update.
Solution: Remove this reminder from 'tezos-baking' package
postinstallation script.
Resolves #482 

[#482] Remove liquidity baking voting reminder from postinst script

---

docker/package/packages.py
docker/package/scripts/tezos-baker-start
docker/package/scripts/tezos-node-start
docker/package/systemd.py

Problem: Currently node services are considered to be up even though it
is yet unable to respond to RPC queries. This requires additional
workarounds for services that depend on node.
Solution: Switch node service to 'Type=notify' and mark service as ready
only once it start to respond to RPC queries.
Resolves #522

[#522] Rework node services startup script

---

docker/package/tezos_setup_wizard.py
docker/package/wizard_structure.py
docs/baking.md

1) Remove obsolete JSON-based faucet support.
2) Add an option to generate a fresh key pair for the baker that needs to be manually filled using the new faucet.
Resolves #525

[#525] Support new faucet

---

flake.nix
nix/build/ocaml-overlay.nix

Problem: It's required to use specific overlay when using NixOS modules
from 'tezos-packaging' flake.
Solution: Expose 'overlay' that includes all required overlays.
Resolves #

[Chore] Expose 'overlay' from flake

---

docker/package/model.py
docker/package/packages.py
meta.json

Problem: kathmandu will soon be activated on
mainnet and we we need to support it in our
services.
Solution: update mainnet services to include
a kathmandu baker for the protocol switch-over
and bump version to make a new release.
None

[Chore] Add kathmandu support to mainnet

---

.buildkite/pipeline-raw.yml
docker/package/model.py
docs/distros/fedora.md

CI fails to run test builds of binary packages for Fedora for two reasons:
1. the CI step has not been updated and tries to build a package that no longer exist
2. the build process on Fedora is broken, as the binary name hasn't been replaced everywhere it should have been
This PR is a quick fixup to solve both these issues (more issues may follow to improve these tho).   
None

[Chore] Fix up binary building on Fedora and CI steps

---

docker/package/model.py
docker/package/packages.py
meta.json

Problem: Fedora packages lack `tezos`-based executables.
Solution: Symlink `octez`-based binaries with `tezos` ones.
Resolves #

[Chore] Symlink new and legacy names on fedora

---

default.nix
flake.nix
nix/default.nix
shell.nix

After rename, tezos-based packages are no longer available. However, they still heavily used in nix infrastructure, as well as 
legacy binary names.
This PR provide it.
Resolves #544 

Provide tezos packages for nix

---

docker/package/Dockerfile-fedora
docker/package/scripts/build-binary.sh
docs/support-policy.md

Problem: Fedora 34 has reached its EOL so,
per our support policy we no longer need to support it. OTOH Fedora 36 is now a stable release so, following the same policy, we should instead support it.
Solution: Support Fedora 36 and deprecate Fedora 34.
Resolves #534 

[#534] Support Fedora 36 and deprecate Fedora 34

---

.buildkite/pipeline-for-tags.yml
.buildkite/pipeline-raw.yml
scripts/autorelease.sh
scripts/publish-native-packages.sh
scripts/update-tezos.sh

Problem: It was decided to substitube current system attribute for impure builds generically, rather than pick
Solution: Update them.
Resolves #

[Chore] Hotfix devShells attribute

---

docker/package/fedora.py
docker/package/model.py

Problem: Systemd services names supplied by tezos-baking packages were lowercased. But fedora scripts still were awaiting initial proto names, so baking setup was failing with error.
Solution:
* Do not lowercase baker services' names.
* Lowercase required services specifically for ubuntu.
Resolves #550 

[#550] Fix instantiated services installation

---

docker/package/model.py
docker/package/packages.py
meta.json

Problem: `tezos-baking` does not depends on `tezos-node`, thus does not install it, resulting in error during setup.
Solution: Add `tezos-node` as native dep for `tezos-baking`.
Resolves #557

[#557] Add `tezos-node` as native dep for `tezos-baking`

---

docs/systemd.md

Problem: The repo has some documentation about using tezos packages with Windows using WSL. However, this usage was severely limited by the lack of official support for `systemd` in WSL, but that's no longer the case, because `systemd` is supported on WSL starting from `0.67.6`.
Solution: Update the docs about using `systemd` services on WSL.
Resolves #533

[#533] Update WSL usage docs with systemd support

---

docker/package/wizard_structure.py

Problem: It's impossible to dry-run delegate registration
on lima due to bug.
Solution: Remove `--dry-run` for now, until
https://gitlab.com/tezos/tezos/-/issues/4200 resolved.
Resolves #564

[#564] Remove dry-run flag

---

README.md
docker/package/model.py
docker/package/tezos_setup_wizard.py
docker/package/tezos_voting_wizard.py
docs/baking.md
docs/service-options.md
docs/tests/voting.md
docs/voting.md

Problem: The names are unnecessarily long and word "wizard" at the end is not all that useful, especially if/when these tools get non-interactive mode implemented.
Solution: Rename to tezos-setup and tezos-vote.
Resolves #569 

[#569] Simplify wizards' names

---

docker/package/tezos_setup_wizard.py
docker/package/wizard_structure.py

This modifies the wizard to handle missing and empty node data directory (most likely to happen when setting a custom one), by creating and configuring them if necessary.
Resolves #571

[#571] Handle empty or missing node data dirs in setup wizard

---

docker/package/scripts/build-binary.sh
flake.nix
nix/build/ocaml-overlay.nix

`tezos` repo on v15.1 tag contains `octez-dev-deps.opam` file, which is redundant, but breaks building through `opam`.
That PR filter it out from both native packages and nix packages build process.
Resolves #

Remove dev deps v15.1 release hotfix

---

flake.lock
tests/test_script.py
tests/tezos-binaries.nix
tests/tezos-modules.nix
tests/tezos-nix-binaries.nix

Problem: We recently updated our nixpkgs fork. However, this repo still uses the old revision.
Solution: Bump nixpkgs.
Resolves #

[Chore] Bump nixpkgs

---

flake.lock
nix/modules/common.nix
nix/modules/tezos-accuser.nix
nix/modules/tezos-baker.nix

1) Support Mumbai and deprecate Katmandu in NixOS modules.
2) Update `nixpkgs` to fix `autorelease-macos` devShell
Resolves None

Chore updates

---

Formula/tezos-accuser-PtLimaPt.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-PtLimaPt.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-node.rb
Formula/tezos-signer.rb
Formula/tezos-smart-rollup-client-PtMumbai.rb
Formula/tezos-smart-rollup-node-PtMumbai.rb
Formula/tezos-tx-rollup-client-PtLimaPt.rb
Formula/tezos-tx-rollup-node-PtLimaPt.rb
flake.lock
flake.nix

Problem: Octez now has 'conf-cmake' opam dependency that requires
'cmake' to be present.
Solution: Add 'cmake' to list of build dependencies for brew formulae.
Resolves #

[Chore] Add 'cmake' to brew build dependencies

---

scripts/update-tezos.sh

Problem: On every new octez upsteam release we reset `letter_version` manually.
Solution: Reset it automatically with script.
Resolves #601
- [] I checked whether I should update the [README](/serokell/tezos-packaging/tree/master/README.md)

[#601] Reset letter_version automatically

---

docker/package/tezos_setup_wizard.py

The format of the snapshot metadata provided by xtz-shots.io has changed and since the `tezos-setup` wizard uses it, this needs to be updated.
See individual commits for more on the specific changes.
Resolves #588 
Related to #441 

[#588] Update tezos-setup wizard to changes in snapshot metadata format

---

docker/package/package_generator.py

Problem: Currently there is no way to provide sources for `tezos-baking` package. But what do we really need is ignore absence of it.
Solution: Let sources for tezos-baking be provided and ignore if they are not.
Resolves #

[Chore] Change logic for tezos-baking sources

---

docker/fetch_tezos_sources.py

Problem: Since last release our way to parse tag from `version.sh` is not relevant anymore.
Solution: Evaluate and output variable contents instead of parsing it.
Resolves #

[Chore] Change way to retrieve opam repository tag

---

docker/package/Dockerfile-ubuntu
docker/package/model.py

Problem: in bd2ecfbf38b22ffd1f744b403e93317889c0ce0c we introduced a lower bound of python to version 3.8 and to do so a specific package is used instead of the generic python3 on both Ubuntu bionic and focal.
This is however only necessary for bionic and it's causing problems on Raspberry Pi OS installations, as there installing python3.8 is not simple (and there is no need to, as the python3 package is for 3.9).
Solution: use the python3 package on both focal and jammy, only use the python3.8 package on bionic.
None, this started because a user reported being unable to install the latest packages on Rasperry Pi OS.

[Chore] Use python3 package in Ubuntu focal packages

---

docker/package/scripts/udev-rules

Problem: Currenly code regarding adding plugdev group does not working as expected, resulting in errors output.
Solution: Use parentheses to prioritize operations properly.
Resolves #

[Chore] Fix plugdev group add

---

docker/package/tezos_setup_wizard.py

This PR mainly prevents the setup wizard from failing/quitting when there is something unexpected in the snapshot metadata format. 
Resolves #612 

[#612] Do not fail on unexpected snapshot metadata formats

---

.buildkite/pipeline-for-tags.yml

Problem: we recently copied a pipeline step from the standard pipeline definition to the one for tags, including 'only_changes' fields that don't work in the latter.
Solution: remove the 'only_changes' settings from the pipeline for tags.
None

[Chore] Remove only_changes from pipeline for tags

---

Formula/tezos-node-mumbainet.rb
docker/package/model.py
docker/package/packages.py
meta.json

This updates `mumbainet`'s definitions to the new URL and prepares for a new release.
None

[Chore] Update mumbainet url

---

.buildkite/pipeline-raw.yml

Problem: we now have a new Mac-based queue for docker builds based on arm64, but the CI steps for the builds are still commented out.
Solution: un-comment and re-enable arm static build CI step.
Resolves #593

[#593] Re-enable arm build steps in CI

---

docker/fetch_tezos_sources.py

Problem: Seems like octez binaries infer their version from git tag, which get erased because `fetch_tezos_sources.py` deletes `tezos/.git` folder, resulting in
`unknown (not-available) (0.0+dev)`
output instead of actual version.
Solution: Preserve `tezos/.git` folder.
Resolves #628 

[#628] Preserve tezos git folder

---

docker/package/model.py
meta.json

Problem: we want to make a new native release to correct the bug that caused #628, so we need to bump the release number.
Solution: bump the release number.
None

[Chore] Bump release number

---

docker/package/meta.py
docker/package/model.py

Problem: v16.0 release was made with slighly malformed sources, resulting in losing version information. Thus, to update sources, it's not enough to bump release version.
Solution: Add letter `b` to all packages' version.
Resolves #

[Chore] Add letter version to all packages

---

docker/docker-tezos-packages.py
docker/package/package_generator.py

Problem: When we make new release based on the same upstream octez version, we have to use previous source archive to upload packages to launchpad. Since they are available on predictable urls, we should have option to fetch them automatically during build.
Solution: Add flag to get sources from launchpad if relevant source archive is absent under `sources-dir` (or it's not defined).
Resolves #

[Chore] Add option to fetch sources from launchpad

---

docker/docker-tezos-packages.py
docker/package/package_generator.py

Problem: For now, we don't really know which artifacts were output
from container. This results in resigning issues because we just
list all files from output folder.
Solution: Get information about exact resulting artifacts from container.
Resolves #

[Chore] Output artifact list from container

---

docker/package/tezos_setup_wizard.py

Problem: the setup wizard can remove (most of) the content of a node data dir if the user chooses to do so instead of keeping it. However, if there is a node service still running, this data dir can be partially re-filled while the wizard is still running and so cause issues, because some node commands need the data dir to be clean.
Solution: Stop the node service in the wizard before cleaning its data directory.
Resolves #642

[#642] Stop node service when removing its data

---

docs/voting.md

Problem: there is a broken link in the voting documentation, which is referencing a file that doesn't exists.
Solution: fix the link to point at a section, as it was intended.
None

[Chore] Fix broken link in voting doc

---

.buildkite/pipeline-for-tags.yml
.buildkite/shell.nix
.gitignore
docker/package/package_generator.py

These PR has a few fixes for changes from #640, see individual commits for more details.
~~Note: it is marked as WIP because there's still an issue with uploading Fedora packages.~~
None

[Chore] Hotfixes for split builds

---

docker/package/tezos_setup_wizard.py

Problem: When snapsnot is provided as local file, it takes a lot of time, because it gets copied under `/tmp` folder, which is excess.
Solution: Use provided snapshot file in-place.
Resolves #654 

[#654] Fix local snapshot import

---

docs/baking.md

I was playing around with this and found `.tezos-client` was in /var/lib/tezos by default.

backing.md: Add tezos/ to directory path.

---

scripts/build-one-bottle.sh

Problem: 'brew install' doesn't allow building dependencies from sources if there is a bottle available. At the same time some bottles require specific values for 'HOMEBREW_CELLAR' and 'HOMEBREW_PREFIX'. As a result, they cannot be installed with a user-specific brew installation (when all brew directories are directly in user HOME directory).
Solution: Install all dependencies prior to the actual bottle build.
Resolves None

[Chore] Install 'brew' formulae deps prior to bottle building

---

docker/package/Dockerfile-ubuntu
docker/package/model.py
docker/supported_versions.json
docs/support-policy.md
docs/ubuntu.md

Problem: Ubuntu 18.04 LTS met its End of Standard Support.
Solution: Remove ubuntu bionic support.
Resolves #

[Chore] Deprecate ubuntu bionic

---

.buildkite/pipeline-for-tags.yml

Problem: our infrastructure now supports running ARM and x64 bottle builds in parallel, but we still avoid that in our pipelines.
Problem: change the pipeline definition to allow ARM and x64 mac builds to run at the same time.
None

[Chore] Run BigSur bottle builds in parallel

---

.buildkite/pipeline-for-tags.yml
docker/build/ubuntu/upload.py
docker/build/util/upload.py

Problem: Albali machine provides copr token only
under `copr-uploader` user, which is different from
buildkite one. Using absolute paths make impossible
for `copr-cli` to upload that files under `sudo -u`.
On the other hand, it doesn't really change script's
intended behavior.
Solution: Use relative paths to artifacts.
Resolves #

[Chore] Fix fedora upload

---

docker/package/model.py
docker/package/packages.py
meta.json

Problem: PtNairob baker should be included already as an option for baking services for ghostnet and mainnet.
Solution: Include it.
Resolves #

[Chore] Add PtNairob instances for nets

---

docker/build/fedora/sign.py
docker/build/fedora/upload.py
docker/build/ubuntu/sign.py
docker/build/ubuntu/upload.py

Problem: copr epel chroot name lacks of version
number, resulting in error during upload.
Solution: Specify correct name.
Resolves #671 

[#671] Fix epel chroot name

---

.buildkite/hooks/pre-exit
.buildkite/pipeline-raw.yml
docker/package/wizard_structure.py
tests/systemd/README.md
tests/systemd/Vagrantfile
tests/systemd/bootstrap.sh
tests/systemd/services_tests.py

This PR introduces tests for systemd services provided by our `.deb` packages with Octez binaries.
Currently, there are tests for `tezos-node`, `tezos-baking`, `tezos-baker`, and `tezos-signer` services.
At the moment, they can only be run locally.
For usage instructions refer to this [README](https://github.com/serokell/tezos-packaging/tree/rvem/%23181-systemd-services-testing/tests/systemd).
Roadmap:
1) ~Integrate these tests into CI. For this, we'll first need to merge #480 to have a fast way of building binary `.deb` packages~
2) ~Provide tests for more services. Perhaps, make these tests a bit safer.~
3) ~Test non-default services configuration~
Resolves #181

[#181] Test systemd services in VM

---

nix/modules/common.nix
tests/tezos-modules.nix

Problem: if you attempt to define a configuration using NixOS modules but decided to disable it, it will still attempt to start module.
Solution: Do not run service on startup if it is disabled and tweak test script according to services' enable option.
Resolves #

[#646] Consider enable option in modules

---

baking/pyproject.toml

Problem: `tox` config is ignored by
fedora 38 build and causes fedora 37 build
to crash.
Solution: Remove it.
Resolves #

[Chore] Remove redundant tox config

---

.buildkite/pipeline-for-tags.yml
Formula/tezos-accuser-PtMumbai.rb
Formula/tezos-accuser-PtNairob.rb
Formula/tezos-baker-PtMumbai.rb
Formula/tezos-baker-PtNairob.rb
Formula/tezos-node-ghostnet.rb
Formula/tezos-node-mainnet.rb
Formula/tezos-node-mumbainet.rb
Formula/tezos-node-nairobinet.rb
Formula/tezos-signer-http.rb
Formula/tezos-signer-https.rb
Formula/tezos-signer-tcp.rb
Formula/tezos-signer-unix.rb
Formula/tezos-smart-rollup-node-PtMumbai.rb
Formula/tezos-smart-rollup-node-PtNairob.rb

This PR has two changes needed for Octez 17.2 release(s):
1. updates formulae after the deprecation of `plist`s
2. stops CI from trying to build for arm64 BigSur
See individual commit messages for additional info.
None

[Chore] Brew bottles hotfixes for v17.2 

---

.buildkite/pipeline-for-tags.yml
Formula/tezos-smart-rollup-node-PtMumbai.rb

This PR follows #683 and:
1. removes a line accidentally left behind there
2. re-enables the pipeline steps to build arm64 bottles for BigSur
None

[Chore] More brew bottles hotfixes for v17.2

---

baking/src/tezos_baking/tezos_setup_wizard.py
docker/package/model.py
docker/package/package_generator.py
docker/package/packages.py
docker/package/ubuntu.py

Problem: Currently, if node snapshot download fails (e.g. for network issues)
this step fails and the user needs to download a snapshot again. This can be very inconvenient as some snapshots are very large and downloading them can take a long time.
Solution: Use `wget` with `--continue` option to be able to resume download.
Resolves #

[#644] Allow setup to resume snapshot download

---

baking/src/tezos_baking/wizard_structure.py

Problem: If the baker key is present already, `tezos-setup` displays its value. It is unnecessary and insecure.
Solution: Display address only.
Resolves #689 

[#689] Do not display baker address value

---

baking/src/tezos_baking/wizard_structure.py

Problem: Output during generated key import
contains typo.
Solution: Fix it.
Resolves #687 

[#687] Fix typo in tezos-setup

---

docker/package/package_generator.py

Problem: Since `9b9cfbb`, ubuntu packages got
runtime deps installed correctly. But they were
excluded from the build deps, though they still
have to be around during build.
Solution: Supply runtime deps as build deps too.
Resolves #

[Chore] Complement ubuntu build deps

---

docker/package/scripts/build-binary.sh
flake.nix
meta.json
nix/build/ocaml-overlay.nix
nix/build/tezos-event-logging.opam

Native packages binary build seem to be broken too, the same reason as the nix build's one. 
The reason is we recursively search for `opam` files in the `tezos` repo and try to use them all. We exclude `octez-dev-deps.opam`, but one more file now should be excluded for the correct build.
Regarding native builds, there is no need to search all opam files recursively at all. All deps are located in one opam file. Commands for binary build are taken from the `tezos` Makefile scripts.
Resolves #

[Chore] v18.0-rc1 hotfixes

---

.github/CONTRIBUTING.md

PR fixes small incorrectness in CONTRIBUTING.ml regarding maintenance.
Resolves #634 

[#634] Update maintenance guides

---

Formula/tezos-accuser-Proxford.rb
Formula/tezos-accuser-PtNairob.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-Proxford.rb
Formula/tezos-baker-PtNairob.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-dac-client.rb
Formula/tezos-dac-node.rb
Formula/tezos-node.rb
Formula/tezos-signer.rb
Formula/tezos-smart-rollup-client-Proxford.rb
Formula/tezos-smart-rollup-client-PtNairob.rb

This MR removes unnecessary dependency of `libffi` from tezos-client build. This seems to be the only dependency that is unnecessary, as without others brew fails to build it.
Closes: #591 

[#591] Remove unnecessary tezos-client deps

---

docker/README.md
docker/build/Dockerfile
docker/build/Dockerfile.aarch64
docker/docker-static-build.sh

Problem: `make static` command utilizes `OCTEZ_EXECUTABLES` variable,
which we can use to specify exact binaries to build. Also, it
could be used to build experimental or development binaries.
Solution: Let user provide `OCTEZ_EXECUTABLES` env var and pass
it to the build.
Resolves #

[Chore] Utilize OCTEZ_EXECUTABLES env var

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/wizard_structure.py

Problem: Since #441 tezos-setup-wizard is using xtz-shots.io metadata for node snapshot files. This metadata provides some information about snapshots e.g. snapshot head block hash, height, and timestamp.
Solution: Output some of it to user.
Resolves #

[#467] Display useful snapshot metadata

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/wizard_structure.py

Problem: The setup wizard currently has an option to use
the metadata provided by xtz-shots (see #441) to download
a snapshot for its node. There are however other snapshot
providers that are adopting the same metadata format, so we want
to let the users pick a different provider too.
Solution: Add the step to choose provider.
Resolves #633
Resolves #692 

[#633] Allow users to specify snapshot provider

---

.github/workflows/build-bottles.yml
Formula/tezos-smart-rollup-wasm-debugger.rb
docker/docker-static-build.sh
docker/package/packages.py
nix/build/release-binaries.nix
scripts/build-all-bottles.sh

There is a demand for octez-smart-rollup-wasm-debugger to be included into release.
Resolves #

[Chore] Support octez-smart-rollup-wasm-debugger 

---

baking/src/tezos_baking/steps.py
baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/tezos_voting_wizard.py
baking/src/tezos_baking/util.py
baking/src/tezos_baking/validators.py
baking/src/tezos_baking/wizard_structure.py

This is preparatory PR for the #568.
Resolves #

[Chore] Factor out code from `wizard_structure`

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/wizard_structure.py

Problem: The setup wizard support a setup with a Ledger device. It often
isn't clear from the wizard itself, however, when an action is expected
from the user, which leads to unnecessary waiting and/or confusion.
Solution: Add visible prompts that an action from user is expected.
Resolves #

[#714] Improve ledger prompts

---

.buildkite/pipeline-for-tags.yml

Problem: when some bottles are build but then the step fails, the build restarts
without re-building the existing bottles.
This causes issues because we pick the bottles from the job's artifacts and we
only receive those from the second run of the job.
Solution: we take the BigSur bottles (after all have been built) from the GitHub
release where they have already been uploaded.
Resolves #539 

[#539] Load BigSur bottles from release instead of artifacts

---

.buildkite/pipeline-raw.yml

Problem: listed `only_changes` files that trigger pipeline steps are outdated.
Solution: Update them.
Resolves #

[Chore] Set correct `only_changes` field for steps

---

baking/src/tezos_baking/tezos_voting_wizard.py

Problem: Reference to `config` wasn't qualified with `self`, resulting in exception.
Solution: Qualify it properly.
Resolves #725

[#725] Fix reference to config

---

baking/pyproject.toml
docker/package/model.py
meta.json

Problem: we have some important fixes, especially for the voting wizard, that should be released soon, as well as other changes that have accumulated since the last release.
As such, we want to make a new one.
Solution: bump the version numbers in preparation for a new release.
None

[Chore] Prepare a new release

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/validators.py

Problem: User provided paths with tilde char does not
pass the validation check.
Solution: Expand tilde char to the home directory.
Resolves #728 

[#728] Expand tilde char in user provided path

---

baking/src/tezos_baking/tezos_setup_wizard.py

Problem: Currently setup wizard tries to download the snapshot only on the same Octez version (see #707) from the provider metadata. However, this is not correct, since snapshot doesn't have to be created with the exact same node version.
Solution: Provide one of these latest snapshots in decreasing order of relevance:
* exact version match
* major version is the same, but lesser minor version
* snapshot version is 6
Resolves #718 

[#718] Improve algorithm of picking snapshot

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/wizard_structure.py

Problem: There is a typo in 'tezos-setup' prompt
message.
Solution: Fix the typo.
Resolves #732

[#732] Fix typo in 'tezos-setup' prompt

---

.github/workflows/test-binaries.yml
.reuse/dep5
docker/tests/Dockerfile-fedora-test
docker/tests/Dockerfile-ubuntu-test
docker/tests/binaries.json
docker/tests/scripts/test-fedora-binaries.sh
docker/tests/scripts/test-ubuntu-binaries.sh
docker/tests/test-fedora-binaries.py
docker/tests/test-ubuntu-binaries.py

This PR adds checks that Tezos binaries can be installed on the latest Ubuntu and Fedora can be installed and work fine. The tests run once every day.
Resolves #641 

[#641] Add tezos binaries tests

---

baking/src/tezos_baking/steps.py
baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/tezos_voting_wizard.py
baking/src/tezos_baking/wizard_structure.py

Problem: Currently we have two wizards, tezos-setup and tezos-vote,
neither of which saves any logs. It's useful sometimes to know
the configuration of the last wizards' call.
Solution: Save the log file with setup configuration.
Resolves #

[#651] Log wizards actions

---

docker/package/scripts/udev-rules

Problem: Post-install script adding udev rules will fail running in container environement and it has checks for it. It doesn't cover all cases though. Specifically, it does not recognize running in k8s environment. According to the
[docs](https://kubernetes.io/docs/tutorials/services/connect-applications-service/#environment-variables) k8s always export `KUBERNETES_SERVICE_HOST` variable.
Solution: Check if `KUBERNETES_SERVICE_HOST` variable is set.
Resolves #

[#734] Do not add udev rules in k8s environment

---

docker/build/build-deps.sh
docker/build/build-tezos.sh

Problem: Since
[!8631](https://gitlab.com/tezos/tezos/-/merge_requests/8631), ocaml-bls12-381 library was moved into tezos/tezos tree, so BLST_PORTABLE set for deps build was ignored.
Solution: Set it for tezos build.
Resolves #

[#735] Set BLST_PORTABLE env var on correct stage

---

Formula/tezos-accuser-Proxford.rb
Formula/tezos-accuser-PtNairob.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-Proxford.rb
Formula/tezos-baker-PtNairob.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-dac-client.rb
Formula/tezos-dac-node.rb
Formula/tezos-node.rb
Formula/tezos-signer.rb
Formula/tezos-smart-rollup-client-Proxford.rb
Formula/tezos-smart-rollup-client-PtNairob.rb
Formula/tezos-smart-rollup-node-Proxford.rb
Formula/tezos-smart-rollup-node-PtNairob.rb
Formula/tezos-smart-rollup-wasm-debugger.rb

Problem: When both arm64 and x86_64 brew installation are present,
linker may pick the libev library for wrong architecture causing the
build to fail.
Solution: Force linker to use libraries from HOMEBREW_PREFIX by setting
'LDFLAGS'.
Resolves #700

[#700] Brew formulae: force linker to use libraries from HOMEBREW_PREFIX

---

docker/tests/scripts/test-fedora-binaries.sh
docker/tests/scripts/test-ubuntu-binaries.sh

Fix small bug in binaries testing script
Resolves #641

[Chore] Fix bug in tests

---

baking/src/tezos_baking/tezos_voting_wizard.py
baking/src/tezos_baking/util.py
baking/src/tezos_baking/wizard_structure.py
docker/package/packages.py
docs/voting-test.md

Problem: Currently, `tezos-vote` does not provide
adequate user prompts and feedback when used with
ledger devices.
Solution: Provide visible prompts requesting action from user.
Resolves #729

[#729] Introduce better prompts for `tezos-vote`

---

baking/pyproject.toml
docker/package/model.py
meta.json

Problem: We should cut out a new release, thus
release number must be bumped.
Solution: Bump it.
Resolves #

[Chore] Bump release version

---

Formula/tezos-accuser-Proxford.rb
Formula/tezos-accuser-PtNairob.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-Proxford.rb
Formula/tezos-baker-PtNairob.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-dac-client.rb
Formula/tezos-dac-node.rb
Formula/tezos-node.rb
Formula/tezos-signer.rb
Formula/tezos-smart-rollup-client-Proxford.rb
Formula/tezos-smart-rollup-client-PtNairob.rb
Formula/tezos-smart-rollup-node-Proxford.rb
Formula/tezos-smart-rollup-node-PtNairob.rb
Formula/tezos-smart-rollup-wasm-debugger.rb

Problem: `octez` now supports `opam` 2.1+, so
workaround with `wget`ing `opam` `2.0.9` could be
removed.
Solution: Remove opam download and use one from the brew.
Resolves #723 

[#723] Use opam from homebrew in formulae

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/tezos_voting_wizard.py
baking/src/tezos_baking/util.py
baking/src/tezos_baking/wizard_structure.py

Problem: the location of the log file is unclear from the message given by the wizards. They also don't attempt to show the logs or suggest how to do it.
Solution: Show last 10 lines of the error output. Suggest how to see the full log. Separate log entries in the file by the dates.
Resolves #705 

[#705] Better show the error logs of the wizards

---

baking/src/tezos_baking/tezos_setup_wizard.py

This PR makes several improvements in the logic of picking the latest compatible snapshot in provider's metadata. See the commit messages to get more details about each improvement.
Resolves #738

[#738] Further improve the algorithm of picking the latest compatible snapshot

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/tezos_voting_wizard.py
baking/src/tezos_baking/wizard_structure.py

Problem: `key_import_mode` key was used to determine ledger use.
But in some execution paths this key never has a value.
Solution: Check ledger use with `check_ledger_use`.
Resolves #

[Chore] Fix ledger use condition

---

.buildkite/pipeline-for-tags.yml
.buildkite/pipeline-raw.yml
.github/workflows/test-binaries.yml

Problem: We introduced rootless docker on albali and now we need to change our docker CI pipelines to use albali runners instead of bunda runners.
Solution: Remove the bunda specific runner tag.
Resolves #

[OPS-1436] Use rootless docker

---

.github/workflows/build-bottles.yml
.github/workflows/check-formulas.yml
.github/workflows/test-binaries.yml

Problem: node16 is now deprecated and github-runner provided by nixpkgs no longer supports this runtime. However, "actions/checkout@v3" uses this runtime.
Solution: Update CI pipeline to use "actions/checkout@v4".
Resolves #

[Chore] Update "actions/checkout"

---

scripts/update-tezos.sh

Problem: It's possible that release number, 'letter_version', and lists of binaries and protocols aren't going to be updated when creating a PR that introduces the new Octez version. However, 'git commit' return non-zero exit code when one attempts to commit empty diff. As a result, 'update-tezos.sh' may fail in CI.
Solution: Supress 'git commit' non-zero exit code.
Resolves #

[Chore] Supress 'git commit' non-zero exit codes in update-tezos.sh

---

docker/package/meta.py
docker/package/update-test-binaries-list.py
docker/tests/binaries.json
scripts/update-tezos.sh

This PR adds a pipeline setup to update the list of binaries after every successful tag build. The script will create a followup PR with an updated list of binaries. 
Resolves #736 

[#736] Add setup to automatically update binaries

---

baking/src/tezos_baking/tezos_setup_wizard.py
baking/src/tezos_baking/validators.py
baking/src/tezos_baking/wizard_structure.py
docs/baking.md

Problem: In ParisB protocol, each baker needs to explicitly stake some
balance (minimum 600tz) to receive baking rights. In case of the bakers
that are registered in Oxford or earlier, they are staked automatically,
but this is not the case for new bakers.
Solution: Check if explicit staking is relevant for the user,
ask for a stake amount and perform staking.
Resolves #793

[#793] Add support of stake operation

---

.buildkite/pipeline-for-tags.yml
.buildkite/pipeline-raw.yml
scripts/bottle-hashes.sh
scripts/build-all-bottles.sh
scripts/update-brew-formulae.sh
scripts/update-tezos.sh
tests/bottle-hashes/test-hash-insert.sh

Problem: new octez releases come with `octez-` prepended to the tag. It doesn't make sense for us to follow this style.
Solution: Strip the prefix and leave only relevant part of tag for us.
Resolves #

[Chore] Fix octez tag handling

---

docker/package/packages.py

Problem: A scheduled job that is supposed to create auto-release on the new Octez release has failed due to an unknown protocol name in 'protocol_numbers'.
Solution: Manually add 'PtParisC' to 'protocol_numbers' with the value '20' (see
https://gitlab.com/tezos/tezos/-/tree/master/src/proto_020_PsParisC).
Resolves #

[Chore] Add 'PtParisC' to 'protocol_numbers'

---

docker/package/packages.py
tests/systemd/Vagrantfile

Problem: testnets usually stop working abruptly. Since `tezos-node` installation process depends on the testnet config being available on certain urls, it fails with error if it can't download one.
Solution: Download list of available testnets at first. Create node configuration only if testnet is still available. Fail the install if `teztnets.json` is not avaialable for download.
Resolves #

[#759] Handle testnet config unavailability

---

docker/package/__init__.py
gen_systemd_service_file.py

Problem: `__init__.py` script gets run every time
we run other scripts from that package. It results in error sometimes, since code inside `packages.py` is not ready to run yet.
Solution: Remove unused imports.
Resolves #

[Chore] Remove unused imports

---

.github/workflows/build-bottles.yml
Formula/tezos-accuser-PsParisC.rb
Formula/tezos-accuser-PtParisB.rb
Formula/tezos-admin-client.rb
Formula/tezos-baker-PsParisC.rb
Formula/tezos-baker-PtParisB.rb
Formula/tezos-client.rb
Formula/tezos-codec.rb
Formula/tezos-dac-client.rb
Formula/tezos-dac-node.rb
Formula/tezos-dal-node.rb
Formula/tezos-node.rb
Formula/tezos-signer.rb
Formula/tezos-smart-rollup-node.rb
Formula/tezos-smart-rollup-wasm-debugger.rb
docs/support-policy.md
scripts/bottle-hashes.sh
scripts/update-brew-formulae.sh
tests/bottle-hashes/test-hash-insert.sh

Problem: we have built brew bottles for the new Octez release, but their hashes
aren't in the formulae yet.
Solution: added the hashes.
Resolves #

[Chore] Add bottle hashes for v20.3-1
