serokell/tezos-packaging

- README.md
- packageRpm.nix
Problem: "Obtain binary or packages from CI" section in the README.md
isn't quite clear. Also, there are some inaccuracies in this file.
Solution: Update README, also update `packageRpm.nix` because it
contained some incorrect stuff.
https://issues.serokell.io/issue/TM-359
> [TM-359] Update README

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/task.md
- .reuse/dep5
Added issue templates. Tested [here](https://github.com/gromakovsky/Task3Translator/issues/new/choose).
GitHub docs about the subject: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
> Update issue templates

- README.md
- default.nix
- scripts/autorelease.sh
Problem: One can be confused by the huge amount of release assets.
Solution: Add some assets description in the README and refer to
this section in release notes.
Resolves #27
> [#27] More descriptive releases

- default.nix
- nix/default.nix
- nix/fix-mainnet.patch
Problem: Current revision that are built and packed are quiet old.
Solution: Update them to the newest existing ones.
Resolves but not really #26
> [#26] Bump tezos branch revisions

- README.md
Problem: After recent update README has some amount on nonsense.
Solution: Reread it and update.
Relates #30
> [#30] Update README

- default.nix
Yet another tezos revision bump
Relates #26
> [#26] Bump master revision

- README.md
> [#19] Hotfix README

- scripts/autorelease.sh
Add stricter failure checks and remove temporary files
> autorelease.sh: add `set -euo pipefail`, clean up on failure

- release.nix
d3feffbc40572a47d5ff30884d91cf61425bce4d commit broke release script, this is attempt to fix it
Resolves #
> Fix release script failing

- default.nix
- nix/default.nix
- nix/fix-master.patch
- nix/static.nix
Problem: https://gitlab.com/tezos/tezos/-/merge_requests/1624 was
merged, changes from this MR is required for some other projects and
it's convenient to use static binaries from this repo in it.
Also, OCaml compiler version for tezos was updated to 4.09.
Solution: Update compiler version, bump various libraries.
Bump master branch revision.
Relates #26
> [#26] Bump master branch revision.

- debSource.nix
- default.nix
- nix/sources.json
Tezos recently had a new v7.1 release, so we are updating our packages and binaries as well.
Relates #26
> [#26] v7.1 release

- .buildkite/pipeline.yml
- .github/CONTRIBUTING.md
- docker/README.md
- docker/build/Dockerfile
- docker/docker-static-build.sh
- docker/docker-ubuntu-packages.sh
- docker/package/Dockerfile
- docker/package/package_generator.py
Fixed instructions in `.github/CONTRIBUTING.md`.
Also added automatic tezos version fetching during static docker build.
Resolves #66
> [#66] improve tezos updating

- .buildkite/pipeline.yml
Problem: Step name was changed, but autoreleasing step wasn't updated
accordingly.
Solution: Update autorelease step.
Resolves #
> Hotfix autoreleasing

- nix/build/hacks.nix
- nix/build/static-overlay.nix
- nix/nix/sources.json
Problem: Current nixpkgs version is quite old and doesn't use our fork.
Solution: Use revision from our fork that uses most of our repos.
Resolves #84 
Relates #97
> [#84] Bump nixpkgs

- docker/build/Dockerfile
- docker/build/Dockerfile.aarch64
- nix/build/hacks.nix
- nix/nix/sources.json
Stable v8.0 has come, we should make new release ASAP.
> v8.0 release

- nix/build/zcash.nix
- nix/nix/sources.json
A new tezos version was released. Even though releases (since v8.1) in tezos repo now have static binaries included, we'd like
to maintain our releases with static binaries for some time.
Resolves #
> v8.1 release

- .buildkite/pipeline.yml
- Formula/tezos-accuser-007-PsDELPH1.rb
- Formula/tezos-accuser-008-PtEdoTez.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-007-PsDELPH1.rb
- Formula/tezos-baker-008-PtEdoTez.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-007-PsDELPH1.rb
- Formula/tezos-endorser-008-PtEdoTez.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer.rb
- Formula/tezos.rb
- README.md
- scripts/build-bottles.sh
Roadmap:
* ~brew formulas for Tezos binaries~
* ~CI sanity check for formulas~
* ~automate brew bottle creation~ ~and incorporate them into the releases~
* ~update README and other usage instructions~
Out of scope of this issue:
* include systemd stuff to the brew packages, see #130 
Testing locally on macOS machine:
```
brew tap serokell/tezos-packaging https://github.com/serokell/tezos-packaging.git
cd /usr/local/Homebrew/Library/Taps/serokell/homebrew-tezos-packaging && git checkout rvem/#103-tezos-brew-formulae
brew install tezos-client # or any other binary
```
Note, that there are no bottles yet, so you'll have to build a package from scratch.
Resolves #103
> [#103] macOS packaging

- .buildkite/pipeline.yml
- .github/pull_request_template.md
- docker/package/Dockerfile-fedora
- docker/package/Dockerfile-ubuntu
- docker/package/defaults/tezos-accuser.conf
- docker/package/defaults/tezos-baker.conf
- docker/package/defaults/tezos-endorser.conf
- docker/package/package_generator.py
- docker/package/packages.py
- docker/package/scripts/tezos-accuser-start
- docker/package/scripts/tezos-baker-start
- docker/package/scripts/tezos-endorser-start
- docker/package/scripts/tezos-node-start
It's time to resurrect native packaging because opam repository was
finally updated. Luckily, the existing packaging approach works nearly out
of the box, only the dependency set should be updated a bit.
Relates #123
> v8.1 native packages

- .buildkite/pipeline.yml
- Formula/tezos-accuser-007-PsDELPH1.rb
- Formula/tezos-accuser-008-PtEdo2Zk.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-007-PsDELPH1.rb
- Formula/tezos-baker-008-PtEdo2Zk.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-007-PsDELPH1.rb
- Formula/tezos-endorser-008-PtEdo2Zk.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer.rb
- FormulaAbstract/tezos.rb
- docker/build/static_libs.patch
- docker/package/packages.py
- nix/build/hacks.nix
- nix/nix/sources.json
- protocols.json
The new Tezos version arrived, we're making a new release as well.
None
> v8.2 Release

- Formula/tezos-accuser-008-PtEdo2Zk.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-008-PtEdo2Zk.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-008-PtEdo2Zk.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer.rb
v8.2-2 bottles were uploaded to the latest release, here we're providing hashes for these bottles.
Resolves #
> v8.2-2 bottles hashes

- README.md
- docs/baking.md
> [#125] 'Baking with tezos-packaging on Ubuntu' article

- .buildkite/pipeline.yml
- docker/build/static_libs.patch
- nix/build/hacks.nix
- nix/nix/sources.json
- protocols.json
- tests/test_script.py
- tests/tezos-nix-binaries.nix
Problem: v9.0-rc1 arrived, we should create a pre-release for it.
Solution: Bump Tezos sources.
Resolves None
> Changes for v9.0-rc1 prerelease

- Formula/tezos-accuser-008-PtEdo2Zk.rb
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-008-PtEdo2Zk.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-008-PtEdo2Zk.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-node-edo2net.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-sapling-params.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- scripts/build-bottles.sh
Updates to the brew formulas for the new `v9.0-rc1` pre-release.
None.
> v9.0-rc1 brew formulas

- .buildkite/pipeline.yml
- Formula/tezos-accuser-008-PtEdo2Zk.rb
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-008-PtEdo2Zk.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-008-PtEdo2Zk.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-node-edo2net.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- docker/build/static_libs.patch
- nix/build/hacks.nix
- nix/nix/sources.json
- protocols.json
- tests/test_script.py
v9.0-rc2 arrived, we should create a pre-release for it.
Resolves None
> v9.0-rc2 prerelease

- Formula/tezos-accuser-008-PtEdo2Zk.rb
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-008-PtEdo2Zk.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-008-PtEdo2Zk.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-node-edo2net.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-sapling-params.rb
- Formula/tezos-signer.rb
New bottles have been built for brew, this adds their hashes in the formulas. 
None
> Update brew formulas bottle hashes for v9.0-rc2

- .buildkite/pipeline.yml
- Formula/tezos-accuser-008-PtEdo2Zk.rb
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-008-PtEdo2Zk.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-008-PtEdo2Zk.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-node-edo2net.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- docker/package/Dockerfile-fedora
- docker/package/Dockerfile-ubuntu
- docker/package/model.py
- docker/package/packages.py
- nix/build/ocaml-overlay.nix
- nix/nix/sources.json
- tests/tezos-nix-binaries.nix
The new Tezos version arrived, as usual, we'd like to make a new release for it.
Resolves None
> v9.0 release

- README.md
- docs/baking.md
Updates the README and baking tutorial with installation info for Raspberry Pi OS.
Resolves #76
> [#76] Document baking on Raspberry Pi OS

- release.nix
Fixes some grammar mistakes in the auto-release template.
None
> [Chore] Fix grammar in auto-release template

- .buildkite/pipeline.yml
- Formula/tezos-accuser-008-PtEdo2Zk.rb
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-008-PtEdo2Zk.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-008-PtEdo2Zk.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-node-edo2net.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- nix/build/hacks.nix
- nix/nix/sources.json
The new Tezos version arrived, as usual, we'd like to make a new release for it.
Resolves None
> v9.1 release

- meta.json
Problem: New version was released.
Solution: Backport release number to 1.
Resolves #
> Change release number to 1

- docs/baking.md
- Rename TLDR section to "Quick Start"
- Add useful details
- Make instructions work for all supported named networks
- Make commands more copy-pasteable
> update docs: improve tldr (quick start)

- .buildkite/filter-pipeline.py
- .buildkite/pipeline-raw.yml
- docker/package/Dockerfile-fedora
- docker/package/Dockerfile-ubuntu
- docker/package/__init__.py
- docker/package/fedora.py
- docker/package/meta.py
- docker/package/model.py
- docker/package/package_generator.py
- docker/package/packages.py
- docker/package/systemd.py
- docker/package/ubuntu.py
There is quite a lot of Python code in the repository now and it doesn't look very well.
This PR provides some refactorings to it:
* Formatting via `black`
* Various refactoring to reduce size of existing modules
Resolves #175
> [#175] Python code refactoring

- meta.json
Problem: We want to release native packages with changes from #204
and #200.
Solution: Bump release number.
Currently based on #208 
Resolves None
> [Chore] Bump release number

- docker/package/tezos_baking_wizard.py
Problem: starting up the tezos-node service takes longer on some machines,
presumably mostly Raspberry Pi's. As we just wait for 5 seconds to allow
the service to start, this leads to the setup wizard checking if the node
has been bootstrapped before the service has even started, so the wizard
crashes because of an ECONNREFUSED error from tezos-client.
Solution: switched from waiting for 5 seconds to checking by requesting
via the RPC interface, every second until the node responds.
Resolves #220
> [#220] Fix checking node before it's started

- .buildkite/pipeline-raw.yml
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-accuser-010-PtGRANAD.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-baker-010-PtGRANAD.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-endorser-010-PtGRANAD.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-granadanet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- meta.json
- nix/nix/sources.json
This PR introduces a new v9.3 release in tezos-packaging.
Follows #
> v9.3 release

- .buildkite/pipeline-raw.yml
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-accuser-010-PtGRANAD.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-baker-010-PtGRANAD.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-endorser-010-PtGRANAD.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-granadanet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- docker/build/Dockerfile
- docker/build/Dockerfile.aarch64
- docker/build/static_libs.patch
- nix/build/hacks.nix
- nix/nix/sources.json
This PR introduces a new v10.0-rc1 release in tezos-packaging.
Currently based on https://github.com/serokell/opam-nix/pull/4
Follows #
script and uploaded them to the created release. Note that for this you'll need a macOS machine running each required version.
> v10.0rc1 release

- docker/package/tezos_baking_wizard.py
Problem: Currently wizard assumes that tezos-client uses default data
directory and node rpc endpoint. However, users may change the default
configuration, which will lead to error in the wizard.
Solution: Gather the following tezos-client specific service constants
from the baking service config: data-directory filepath, baker account
alias, and node rpc endpoint.
Resolves #233
> [#233] Get client specific constants from config

- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-accuser-010-PtGRANAD.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-baker-010-PtGRANAD.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-endorser-010-PtGRANAD.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-granadanet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- docker/build/static_libs.patch
- nix/build/hacks.nix
- nix/nix/sources.json
This PR introduces a new v9.4 release in tezos-packaging.
Follows #
script and uploaded them to the created release. Note that for this you'll need a macOS machine running each required version.
> v9.4 release

- docker/package/tezos_baking_wizard.py
Problem: in the baking wizard we use the `subrocess` lib for calling
external processes like `systemctl`. The API changed slightly from
Python 3.6 to 3.7, we need to support Ubuntu 18.04 which by default
has the former, and right now the wizard consistently crashes on it.
Solution: added the differentiation for the culprit method
`subprocess.run` for whether or not to use the `capture_output` parameter
based on the Python version running the wizard.
Resolves #242 
> [#242] Fix baking wizard failing on Python 3.6

- docker/package/tezos_setup_wizard.py
Problem: currently, if the Tezos setup wizard is used on a testnet,
the "This is NOT the Tezos Mainnet." warning is shown multiple
times, which disrupts the flow of the setup.
Solution: suppressed the warning by temporarily passing the
approppriate environment variable with every tezos-client call.
Resolves #255 
> [#255] Suppress Tezos testnet warning

- docker/package/tezos_setup_wizard.py
Problem: Currently the connected ledger is needed to get the list of the
ledger-stored keys. However, we ask the user to open the baking app after
calling 'tezos-client list connected ledgers'. As a result, the user can
be stuck during setup by being unable to choose the key because the
provided list of ledger-stored keys will be empty.
Solution: Ask the user to open the Baking app and wait until it's opened before
running `tezos-client list connected ledgers`.
Resolves #254
> [#254] Wait for Baking ledger app

- .buildkite/pipeline-raw.yml
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-accuser-010-PtGRANAD.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-baker-010-PtGRANAD.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-endorser-010-PtGRANAD.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-granadanet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- docker/build/static_libs.patch
- nix/build/hacks.nix
- nix/nix/sources.json
This PR introduces a new v10.0-rc2 release in tezos-packaging.
Follows #
> v10.0-rc2 release

- README.md
This is a followup PR to address some feedback receive after #253 to further simplify the README.
An explanation for each of the changes is provided in their respective commit.
Related to #251
> [#251] further README simplifications

- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-accuser-010-PtGRANAD.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-baker-010-PtGRANAD.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-endorser-010-PtGRANAD.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-granadanet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- docker/build/static_libs.patch
- docker/package/model.py
- docker/package/package_generator.py
- meta.json
- nix/build/hacks.nix
- nix/nix/sources.json
This PR introduces a new v9.5 release in tezos-packaging.
Follows #
> v9.5 release

- docker/package/tezos_setup_wizard.py
Problem: Currently it's possible to choose one of the four ledger keys
provided by tezos-client by default or type a ledger url manually.
However, we don't properly validate that ledger url is valid.
Instead, we should provide a way to choose a derivation path that will be
used with the current ledger device.
Solution: Make it possible to provide custom derivation path instead of
the whole ledger url. Once the derivation is provided it appears in the
list of possible ledger urls to choose from. As an addition, an option
to go back to the baker key import process beginning is added.
New prompt:
Resolves #256
> [#256] Improve ledger import prompt

- .github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
- Formula/tezos-accuser-009-PsFLoren.rb
- Formula/tezos-accuser-010-PtGRANAD.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-009-PsFLoren.rb
- Formula/tezos-baker-010-PtGRANAD.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-009-PsFLoren.rb
- Formula/tezos-endorser-010-PtGRANAD.rb
- Formula/tezos-node-florencenet.rb
- Formula/tezos-node-granadanet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- nix/nix/sources.json
This PR introduces a new v9.6 release in tezos-packaging.
Follows #
> v9.6 release

- docker/package/tezos_setup_wizard.py
Problem: to suppress the "This is NOT the Tezos Mainnet" warning, we currently propagate the whole environment through `sudo`. This leads to `HOME` being preserved under `sudo -u tezos`, and `tezos-client` creating its directory in the original user `HOME`.
Solution: changed all the tezos-client calls to directly pass the one environment variable needed for this, `TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER`, instead of the whole env.
Resolves #276 
> [#276] Pass one env var to suppress testnet warning

- Formula/tezos-accuser-010-PtGRANAD.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-010-PtGRANAD.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-endorser-010-PtGRANAD.rb
- Formula/tezos-node-granadanet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-sandbox.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- nix/nix/sources.json
This PR introduces a new  release in tezos-packaging.
Follows #
The opam-repository revision should be the same as the one defined in
[`tezos/tezos`](https://gitlab.com/tezos/tezos/-/blob/master/scripts/version.sh) for the relevant tag.
> v10.1 release

- docker/package/tezos_setup_wizard.py
Problem: when only the node is being set up, currently the setup wizard waits for the node to bootstrap before exiting. `Ctrl+C` during this time undoes all the previous efforts and kills the `tezos-node` service. We would like to be able to leave the node to bootstrap on its own at this point.
Solution: changed the wizard to print instructions and exit upon finishing node setup in case no baking setup is required.
Also fixed a bug where tezos binaries wouldn't pick up files in the user's home directory by prior copying passed snapshot and faucet json files to `/tmp`.
Resolves #315 
> [#315] Change Ctrl+C behaviour to confirm exit

- docker/package/tezos_setup_wizard.py
Problem: there is a use-case for being able to reconstruct storage to run an archive node when importing a full snapshot. The Setup Wizard at the moment doesn't support running archive nodes in any capacity except by manually changing the code, which isn't very convenient.
Solution: if the snapshot the user wants to import is in full history mode, inquire whether the storage should be reconstructed to yield an archive node.
Resolves #364 
> [#364] Support archive nodes from snapshot import

- docker/package/tezos_setup_wizard.py
Problem: currently, the only history mode support present in the Tezos Setup Wizard is the ability to reconstruct an archive mode when importing a full snapshot, and to import either a full or a rolling snapshot. This means we have no history mode support for syncing the node from scratch, and the default mode is 'full', which might not be reasonable.
Solution: added a new step in the wizard, asking about the preferred history mode in case the user skips snapshot import.
Resolves #366 
> [#366] Add history mode support in setup wizard

- docker/package/tezos_setup_wizard.py
Problem: Setup shows incorrect data when multiple ledgers are connected
and have the Baking app open.
Solution: Properly support a case when multiple ledgers are connected.
Explicitly show the ledger URL in the list of derivations. Additionally,
allow choosing a ledger when specifying additional derivations.
Relates #379 (the issue will be resolved once updated `tezos-baking` package is published)
> [#379] Support multiple ledgers connection in setup wizard

- README.md
- docs/baking.md
- docs/voting.md
Problem: we now have released Tezos Voting Wizard, but there's no documentation
on how to use it.
Solution: added a doc on voting as well as documented how to set up a
custom baking instance and use it for voting.
Resolves #389 
> [#389] Document the voting wizard

- scripts/update-tezos.sh
Problem: our Octez distribution releases are mostly automated, but
we still have to automatically reset the release number if we have
made manual releases in the meantime.
Solution: added making another commit that resets the release number
to 1 to the automated initial PR process.
Resolves #431
> [#431] Reset release number in automated releases

- docker/package/tezos_setup_wizard.py
- docker/package/wizard_structure.py
Problem: one of the options for key management is using remote
signers. However, Tezos Setup Wizard currently doesn't support it.
Solution: added remote as one of the options for key import.
Resolves #397 
> [#397] Support remote signers in setup wizard

- nix/modules/common.nix
- nix/modules/tezos-accuser.nix
- nix/modules/tezos-baker.nix
- nix/modules/tezos-node.nix
- tests/tezos-modules.nix
This PR adds a few options to the existing NixOS modules with background Octez daemons.
https://issues.serokell.io/issue/TM-645
> [Chore] More tezos modules options

- nix/modules/common.nix
Problem: Currently modules don't support password-encrypted keys.
Solution: Add a password-filename option that allows providing password
for the password-endcrypted keys.
Resolves #
> [Chore] Add password-filename daemons' modules option

- scripts/update-tezos.sh
> [Chore] update-tezos.sh hotfix

- .buildkite/pipeline-for-tags.yml
- Formula/tezos-accuser-013-PtJakart.rb
- Formula/tezos-accuser-014-PtKathma.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-013-PtJakart.rb
- Formula/tezos-baker-014-PtKathma.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-node.rb
- Formula/tezos-signer.rb
- docker/package/package_generator.py
- flake.nix
- scripts/build-all-bottles.sh
> v14.0~rc1 release hotfixes

- Formula/tezos-tx-rollup-client-013-PtJakart.rb
- Formula/tezos-tx-rollup-client-014-PtKathma.rb
- Formula/tezos-tx-rollup-node-013-PtJakart.rb
- Formula/tezos-tx-rollup-node-014-PtKathma.rb
- README.md
- docker/docker-static-build.sh
- docker/package/defaults/tezos-rollup-node.conf
- docker/package/packages.py
- docker/package/scripts/tezos-rollup-node-start
- docs/tx_rollup.md
- nix/build/release-binaries.nix
Adds support for transaction rollup binaries.
Resolves #453 
> [#453] package rollup binaries

- Formula/tezos-accuser-013-PtJakart.rb
- Formula/tezos-accuser-014-PtKathma.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-013-PtJakart.rb
- Formula/tezos-baker-014-PtKathma.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-node.rb
- Formula/tezos-signer.rb
- Formula/tezos-tx-rollup-client-013-PtJakart.rb
- Formula/tezos-tx-rollup-client-014-PtKathma.rb
- Formula/tezos-tx-rollup-node-013-PtJakart.rb
- Formula/tezos-tx-rollup-node-014-PtKathma.rb
- docker/build/build-tezos.sh
> [Chore] Hotfix brew builds

- docker/package/tezos_setup_wizard.py
Problem: in Tezos Setup Wizard, we allow to automatically download a suitable snapshot from xtz-shots.io. The links have a set pattern that we can predict and reuse, but it's not necessarily a stable solution. xtz-shots.io recently added a metadata JSON to their site, and using it to get snapshot URLs would be more robust.
Solution: switched the snapshot download step to fetching snapshot metadata from base.json and choosing the most recent available entry to offer as options.
Follows #441
> [#441] Use xtz-shots.io snapshot metadata

- docker/package/tezos_setup_wizard.py
Problem: octez-node has a 'block' option when importing a snapshot that can be used to ensure that the block that is imported is the one matching the given hash.
We can collect the block hash from the metadata (when one is available), but the setup wizard doesn't use this info.
Solution: get the block hash when fetching snapshots from metadata and use it during import in the setup wizard.
Resolves #572
> [#572] Use block hash from snapshot metadata in setup wizard

- .buildkite/pipeline-raw.yml
- .gitignore
Small fixes and improvements before a new release, see individual commits for explanation.
None
> [Chore] pre-release hotfixes

- .buildkite/pipeline-raw.yml
- docker/docker-static-build.sh
- nix/build/release-binaries.nix
- protocols.json
See individual commit messages.
None
> [Chore] Hotfixes for v16.0 rc1

- .buildkite/pipeline-for-tags.yml
- .buildkite/pipeline-raw.yml
- docker/build/Dockerfile
- docker/build/Dockerfile.aarch64
- docker/build/build-deps.sh
- docker/build/build-tezos.sh
- docker/build/build-upx.sh
- docker/docker-tezos-packages.py
- docker/fetch_tezos_sources.py
- docker/package/Dockerfile-fedora
- docker/package/Dockerfile-ubuntu
- docker/package/model.py
- shell.nix
Problem: Dependencies and sources were not reused
and rebuilt every time, despite they are about the
same for all packages.
Solution: Refactor Dockerfiles, split stages in different scripts and
place them in separate layers to reuse results using docker cache system.
Resolves #
> [Chore] Optimize docker builds

- Formula/tezos-accuser-PtMumbai.rb
- Formula/tezos-baker-PtMumbai.rb
Problem: Wrong source paths were specified.
Solution: Specify correct ones.
Resolves #
> [Chore] Fix baker and accuser mumbai formulae

- docker/package/tezos_voting_wizard.py
Problem: voting (including with our wizard) using a ledger device requires switching to the wallet app. If there is a local baking setup running this also means that this will be interrupted until the Baking app is opened on the ledger again.
Moreover, because of tezos/#4486 this is no longer sufficient and the baker process needs to be restarted.
Solution: modify the voting wizard so that if one votes with a ledger that is also used for a local baking setup, then at the end of the voting process, the wizar:
1. waits for the baking app to be opened again
2. restarts the baker process(es) involved
Resolves #606
> [#606] Restart baking service after voting if necessary

- tests/README.md
Problem: Self-signed certificate for testing gets expired every two years, so there should be documentation how to renew it.
Solution: Provide steps how to generate certificate.
Resolves #
> [Chore] Document how to issue certificate

- nix/build/release-binaries.nix
This PR updates the documentation for tezos-binaries, adding links to the corresponding articles in octez documentation
Closes: #102 
> [#102] Update documetnation for  tezos binaries

- baking/src/tezos_baking/tezos_setup_wizard.py
- scripts/build-all-bottles.sh
> [Chore] v18.1 release hotfixes

- baking/pyproject.toml
- docker/package/model.py
- meta.json
> [Chore] Bump release version

- baking/src/tezos_baking/tezos_setup_wizard.py
Problem: Sometimes at point of `register_baker` action key is already registered as delegate, resulting in error output.
Solution: Check if it already registered.
Resolves #
> [#755] Check if bakey key already registered

- .reuse/dep5
- docker/active-protocols
- docker/docker-static-build.sh
- docker/octez-executables
- scripts/shell.nix
- scripts/update-release-binaries.py
- scripts/update-tezos.sh
- shell.nix
> [#736] Use binaries list from octez and partially automate binaries update

- baking/src/tezos_baking/provider.py
- baking/src/tezos_baking/tezos_setup_wizard.py
TzInit provider should be supported, as it seems to be the most stable in the near future.
Resolves #782 
> [#782] Support tzinit provider

- Formula/tezos-accuser-Proxford.rb
- Formula/tezos-accuser-PtParisB.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-Proxford.rb
- Formula/tezos-baker-PtParisB.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-dac-client.rb
- Formula/tezos-dac-node.rb
- Formula/tezos-node.rb
- Formula/tezos-signer.rb
- Formula/tezos-smart-rollup-node.rb
- Formula/tezos-smart-rollup-wasm-debugger.rb
- docker/package/package_generator.py
> [Chore] Add deps for v20.0-rc1 binaries

- release.nix
- scripts/update-brew-formulae.sh
> [Chore] Fix license path for release.nix

- docker/package/update-test-binaries-list.py
- docker/tests/binaries.json
> [#736] Hotfix automatic test binaries update

- baking/src/tezos_baking/steps.py
- baking/src/tezos_baking/tezos_setup_wizard.py
- docker/package/packages.py
- docs/baking.md
- docs/systemd.md
> [Chore] Support paris2net instead of parisnet

- Formula/tezos-accuser-Proxford.rb
- Formula/tezos-accuser-PtParisB.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-Proxford.rb
- Formula/tezos-baker-PtParisB.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-dac-client.rb
- Formula/tezos-dac-node.rb
- Formula/tezos-dal-node.rb
- Formula/tezos-node-ghostnet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- Formula/tezos-smart-rollup-node.rb
- Formula/tezos-smart-rollup-wasm-debugger.rb
- meta.json
> [Chore] v20.0-2 release

- Formula/tezos-accuser-Proxford.rb
- Formula/tezos-accuser-PtParisB.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-Proxford.rb
- Formula/tezos-baker-PtParisB.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-dac-client.rb
- Formula/tezos-dac-node.rb
- Formula/tezos-dal-node.rb
- Formula/tezos-node.rb
- Formula/tezos-signer.rb
- Formula/tezos-smart-rollup-node.rb
- Formula/tezos-smart-rollup-wasm-debugger.rb
> [Chore] Add bottle hashes for v20.0-2

- baking/pyproject.toml
- baking/src/tezos_baking/wizard_structure.py
- docker/package/model.py
- docker/package/packages.py
- meta.json
> [Chore] Prepare v20.0-3 release

- docker/package/packages.py
> [Chore] s/PtParisC/PsParisC

- .buildkite/pipeline-for-tags.yml
- Formula/tezos-accuser-PsParisC.rb
- Formula/tezos-accuser-PtParisB.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-PsParisC.rb
- Formula/tezos-baker-PtParisB.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-dac-client.rb
- Formula/tezos-dac-node.rb
- Formula/tezos-dal-node.rb
- Formula/tezos-node-ghostnet.rb
- Formula/tezos-node-mainnet.rb
- Formula/tezos-node.rb
- Formula/tezos-signer-http.rb
- Formula/tezos-signer-https.rb
- Formula/tezos-signer-tcp.rb
- Formula/tezos-signer-unix.rb
- Formula/tezos-signer.rb
- Formula/tezos-smart-rollup-node.rb
- Formula/tezos-smart-rollup-wasm-debugger.rb
Two small hotfixes for PsParisC brew Formulae. I somehow missed these issues in #807:(
Resolves #
> [Chore] hotfix PsParisC brew formulae

- docker/package/Dockerfile-fedora
- docker/package/Dockerfile-ubuntu
- docker/package/package_generator.py
- docker/package/scripts/build-binary.sh
- meta.json
> [Chore] Fix fedora 40 builds

- docker/vendor-rust-deps.py
- meta.json
> [Chore] Fix v22.0-rc1 native packages

- Formula/tezos-accuser-PsQuebec.rb
- Formula/tezos-accuser-PsRiotum.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-PsQuebec.rb
- Formula/tezos-baker-PsRiotum.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-dal-node.rb
- Formula/tezos-node.rb
- Formula/tezos-signer.rb
- Formula/tezos-smart-rollup-node.rb
- Formula/tezos-smart-rollup-wasm-debugger.rb
> [Chore] Add v22.0-rc3-1 hashes to brew formulae for Ventura

- Formula/tezos-experimental-agnostic-baker.rb
> [Chore] Add formula for agnostic baker

- Formula/tezos-accuser-PsQuebec.rb
- Formula/tezos-accuser-PsRiotum.rb
- Formula/tezos-admin-client.rb
- Formula/tezos-baker-PsQuebec.rb
- Formula/tezos-baker-PsRiotum.rb
- Formula/tezos-client.rb
- Formula/tezos-codec.rb
- Formula/tezos-dal-node.rb
- Formula/tezos-node.rb
- Formula/tezos-signer.rb
- Formula/tezos-smart-rollup-node.rb
- Formula/tezos-smart-rollup-wasm-debugger.rb
> [Chore] Remove leftover hashes

- baking/pyproject.toml
- docker/package/model.py
- docker/package/packages.py
- meta.json
> [Chore] Add Riotum baker for mainnet and ghostnest
